// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: pkg/corepb/common.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction the token pages in, relative to where it was issued.
type PaginationToken_Type int32

const (
	PaginationToken_INVALID  PaginationToken_Type = 0
	PaginationToken_NEXT     PaginationToken_Type = 1
	PaginationToken_PREVIOUS PaginationToken_Type = 2
)

// Enum value maps for PaginationToken_Type.
var (
	PaginationToken_Type_name = map[int32]string{
		0: "INVALID",
		1: "NEXT",
		2: "PREVIOUS",
	}
	PaginationToken_Type_value = map[string]int32{
		"INVALID":  0,
		"NEXT":     1,
		"PREVIOUS": 2,
	}
)

func (x PaginationToken_Type) Enum() *PaginationToken_Type {
	p := new(PaginationToken_Type)
	*p = x
	return p
}

func (x PaginationToken_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaginationToken_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_common_proto_enumTypes[0].Descriptor()
}

func (PaginationToken_Type) Type() protoreflect.EnumType {
	return &file_pkg_corepb_common_proto_enumTypes[0]
}

func (x PaginationToken_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaginationToken_Type.Descriptor instead.
func (PaginationToken_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{0, 0}
}

// PaginationToken is an opaque cursor into a paginated list. Callers receive it
// in a list response and pass it back verbatim to fetch the adjacent page; the
// encoded value is an internal store key and must not be parsed by clients.
type PaginationToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  PaginationToken_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=com.evrblk.moab.corepb.PaginationToken_Type" json:"type,omitempty"`
	// Opaque encoded position (an internal store key); do not interpret.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationToken) Reset() {
	*x = PaginationToken{}
	mi := &file_pkg_corepb_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationToken) ProtoMessage() {}

func (x *PaginationToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationToken.ProtoReflect.Descriptor instead.
func (*PaginationToken) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationToken) GetType() PaginationToken_Type {
	if x != nil {
		return x.Type
	}
	return PaginationToken_INVALID
}

func (x *PaginationToken) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RetryStrategy struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RetryIntervalsInSeconds []int64                `protobuf:"varint,1,rep,packed,name=retry_intervals_in_seconds,json=retryIntervalsInSeconds,proto3" json:"retry_intervals_in_seconds,omitempty"` // TODO: add JitterVariance
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RetryStrategy) Reset() {
	*x = RetryStrategy{}
	mi := &file_pkg_corepb_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryStrategy) ProtoMessage() {}

func (x *RetryStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryStrategy.ProtoReflect.Descriptor instead.
func (*RetryStrategy) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_common_proto_rawDescGZIP(), []int{1}
}

func (x *RetryStrategy) GetRetryIntervalsInSeconds() []int64 {
	if x != nil {
		return x.RetryIntervalsInSeconds
	}
	return nil
}

var File_pkg_corepb_common_proto protoreflect.FileDescriptor

const file_pkg_corepb_common_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/corepb/common.proto\x12\x16com.evrblk.moab.corepb\"\x96\x01\n" +
	"\x0fPaginationToken\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.com.evrblk.moab.corepb.PaginationToken.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"+\n" +
	"\x04Type\x12\v\n" +
	"\aINVALID\x10\x00\x12\b\n" +
	"\x04NEXT\x10\x01\x12\f\n" +
	"\bPREVIOUS\x10\x02\"L\n" +
	"\rRetryStrategy\x12;\n" +
	"\x1aretry_intervals_in_seconds\x18\x01 \x03(\x03R\x17retryIntervalsInSecondsB#Z!github.com/evrblk/moab/pkg/corepbb\x06proto3"

var (
	file_pkg_corepb_common_proto_rawDescOnce sync.Once
	file_pkg_corepb_common_proto_rawDescData []byte
)

func file_pkg_corepb_common_proto_rawDescGZIP() []byte {
	file_pkg_corepb_common_proto_rawDescOnce.Do(func() {
		file_pkg_corepb_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_corepb_common_proto_rawDesc), len(file_pkg_corepb_common_proto_rawDesc)))
	})
	return file_pkg_corepb_common_proto_rawDescData
}

var file_pkg_corepb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_corepb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_corepb_common_proto_goTypes = []any{
	(PaginationToken_Type)(0), // 0: com.evrblk.moab.corepb.PaginationToken.Type
	(*PaginationToken)(nil),   // 1: com.evrblk.moab.corepb.PaginationToken
	(*RetryStrategy)(nil),     // 2: com.evrblk.moab.corepb.RetryStrategy
}
var file_pkg_corepb_common_proto_depIdxs = []int32{
	0, // 0: com.evrblk.moab.corepb.PaginationToken.type:type_name -> com.evrblk.moab.corepb.PaginationToken.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_corepb_common_proto_init() }
func file_pkg_corepb_common_proto_init() {
	if File_pkg_corepb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_corepb_common_proto_rawDesc), len(file_pkg_corepb_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_corepb_common_proto_goTypes,
		DependencyIndexes: file_pkg_corepb_common_proto_depIdxs,
		EnumInfos:         file_pkg_corepb_common_proto_enumTypes,
		MessageInfos:      file_pkg_corepb_common_proto_msgTypes,
	}.Build()
	File_pkg_corepb_common_proto = out.File
	file_pkg_corepb_common_proto_goTypes = nil
	file_pkg_corepb_common_proto_depIdxs = nil
}
