// Code generated by genmarshal. DO NOT EDIT.

package corepb

import "encoding"

// CreateQueueRequest

var _ encoding.BinaryMarshaler = (*CreateQueueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateQueueRequest)(nil)

func (m *CreateQueueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateQueueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateQueueResponse

var _ encoding.BinaryMarshaler = (*CreateQueueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateQueueResponse)(nil)

func (m *CreateQueueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateQueueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateScheduleRequest

var _ encoding.BinaryMarshaler = (*CreateScheduleRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateScheduleRequest)(nil)

func (m *CreateScheduleRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateScheduleRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// CreateScheduleResponse

var _ encoding.BinaryMarshaler = (*CreateScheduleResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*CreateScheduleResponse)(nil)

func (m *CreateScheduleResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *CreateScheduleResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeadLetterQueueConfig

var _ encoding.BinaryMarshaler = (*DeadLetterQueueConfig)(nil)
var _ encoding.BinaryUnmarshaler = (*DeadLetterQueueConfig)(nil)

func (m *DeadLetterQueueConfig) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeadLetterQueueConfig) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteQueueRequest

var _ encoding.BinaryMarshaler = (*DeleteQueueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteQueueRequest)(nil)

func (m *DeleteQueueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteQueueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteQueueResponse

var _ encoding.BinaryMarshaler = (*DeleteQueueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteQueueResponse)(nil)

func (m *DeleteQueueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteQueueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteScheduleRequest

var _ encoding.BinaryMarshaler = (*DeleteScheduleRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteScheduleRequest)(nil)

func (m *DeleteScheduleRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteScheduleRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteScheduleResponse

var _ encoding.BinaryMarshaler = (*DeleteScheduleResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteScheduleResponse)(nil)

func (m *DeleteScheduleResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteScheduleResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteTasksRequest

var _ encoding.BinaryMarshaler = (*DeleteTasksRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteTasksRequest)(nil)

func (m *DeleteTasksRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteTasksRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DeleteTasksResponse

var _ encoding.BinaryMarshaler = (*DeleteTasksResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DeleteTasksResponse)(nil)

func (m *DeleteTasksResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DeleteTasksResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DequeSchedulesRequest

var _ encoding.BinaryMarshaler = (*DequeSchedulesRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DequeSchedulesRequest)(nil)

func (m *DequeSchedulesRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DequeSchedulesRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DequeSchedulesResponse

var _ encoding.BinaryMarshaler = (*DequeSchedulesResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DequeSchedulesResponse)(nil)

func (m *DequeSchedulesResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DequeSchedulesResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DequeSchedulesResponseEntry

var _ encoding.BinaryMarshaler = (*DequeSchedulesResponseEntry)(nil)
var _ encoding.BinaryUnmarshaler = (*DequeSchedulesResponseEntry)(nil)

func (m *DequeSchedulesResponseEntry) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DequeSchedulesResponseEntry) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DequeueRequest

var _ encoding.BinaryMarshaler = (*DequeueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*DequeueRequest)(nil)

func (m *DequeueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DequeueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DequeueResponse

var _ encoding.BinaryMarshaler = (*DequeueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*DequeueResponse)(nil)

func (m *DequeueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DequeueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// DequeuingSettings

var _ encoding.BinaryMarshaler = (*DequeuingSettings)(nil)
var _ encoding.BinaryUnmarshaler = (*DequeuingSettings)(nil)

func (m *DequeuingSettings) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *DequeuingSettings) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// EnqueueRequest

var _ encoding.BinaryMarshaler = (*EnqueueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*EnqueueRequest)(nil)

func (m *EnqueueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *EnqueueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// EnqueueRequestEntry

var _ encoding.BinaryMarshaler = (*EnqueueRequestEntry)(nil)
var _ encoding.BinaryUnmarshaler = (*EnqueueRequestEntry)(nil)

func (m *EnqueueRequestEntry) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *EnqueueRequestEntry) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// EnqueueResponse

var _ encoding.BinaryMarshaler = (*EnqueueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*EnqueueResponse)(nil)

func (m *EnqueueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *EnqueueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ExpirationIndexRecord

var _ encoding.BinaryMarshaler = (*ExpirationIndexRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*ExpirationIndexRecord)(nil)

func (m *ExpirationIndexRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ExpirationIndexRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetQueueByNameRequest

var _ encoding.BinaryMarshaler = (*GetQueueByNameRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetQueueByNameRequest)(nil)

func (m *GetQueueByNameRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetQueueByNameRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetQueueByNameResponse

var _ encoding.BinaryMarshaler = (*GetQueueByNameResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetQueueByNameResponse)(nil)

func (m *GetQueueByNameResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetQueueByNameResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetQueueRequest

var _ encoding.BinaryMarshaler = (*GetQueueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetQueueRequest)(nil)

func (m *GetQueueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetQueueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetQueueResponse

var _ encoding.BinaryMarshaler = (*GetQueueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetQueueResponse)(nil)

func (m *GetQueueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetQueueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetScheduleRequest

var _ encoding.BinaryMarshaler = (*GetScheduleRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetScheduleRequest)(nil)

func (m *GetScheduleRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetScheduleRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetScheduleResponse

var _ encoding.BinaryMarshaler = (*GetScheduleResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetScheduleResponse)(nil)

func (m *GetScheduleResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetScheduleResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetStatisticsRequest

var _ encoding.BinaryMarshaler = (*GetStatisticsRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetStatisticsRequest)(nil)

func (m *GetStatisticsRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetStatisticsRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetStatisticsResponse

var _ encoding.BinaryMarshaler = (*GetStatisticsResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetStatisticsResponse)(nil)

func (m *GetStatisticsResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetStatisticsResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetTaskRequest

var _ encoding.BinaryMarshaler = (*GetTaskRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*GetTaskRequest)(nil)

func (m *GetTaskRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetTaskRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// GetTaskResponse

var _ encoding.BinaryMarshaler = (*GetTaskResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*GetTaskResponse)(nil)

func (m *GetTaskResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *GetTaskResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListQueuesRequest

var _ encoding.BinaryMarshaler = (*ListQueuesRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListQueuesRequest)(nil)

func (m *ListQueuesRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListQueuesRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListQueuesResponse

var _ encoding.BinaryMarshaler = (*ListQueuesResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListQueuesResponse)(nil)

func (m *ListQueuesResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListQueuesResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSchedulesRequest

var _ encoding.BinaryMarshaler = (*ListSchedulesRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSchedulesRequest)(nil)

func (m *ListSchedulesRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSchedulesRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListSchedulesResponse

var _ encoding.BinaryMarshaler = (*ListSchedulesResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListSchedulesResponse)(nil)

func (m *ListSchedulesResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListSchedulesResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListTasksRequest

var _ encoding.BinaryMarshaler = (*ListTasksRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ListTasksRequest)(nil)

func (m *ListTasksRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListTasksRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ListTasksResponse

var _ encoding.BinaryMarshaler = (*ListTasksResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ListTasksResponse)(nil)

func (m *ListTasksResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ListTasksResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// PaginationToken

var _ encoding.BinaryMarshaler = (*PaginationToken)(nil)
var _ encoding.BinaryUnmarshaler = (*PaginationToken)(nil)

func (m *PaginationToken) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *PaginationToken) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// PurgeQueueRequest

var _ encoding.BinaryMarshaler = (*PurgeQueueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*PurgeQueueRequest)(nil)

func (m *PurgeQueueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *PurgeQueueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// PurgeQueueResponse

var _ encoding.BinaryMarshaler = (*PurgeQueueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*PurgeQueueResponse)(nil)

func (m *PurgeQueueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *PurgeQueueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Queue

var _ encoding.BinaryMarshaler = (*Queue)(nil)
var _ encoding.BinaryUnmarshaler = (*Queue)(nil)

func (m *Queue) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Queue) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// QueueId

var _ encoding.BinaryMarshaler = (*QueueId)(nil)
var _ encoding.BinaryUnmarshaler = (*QueueId)(nil)

func (m *QueueId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *QueueId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// QueueState

var _ encoding.BinaryMarshaler = (*QueueState)(nil)
var _ encoding.BinaryUnmarshaler = (*QueueState)(nil)

func (m *QueueState) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *QueueState) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// QueuesCounter

var _ encoding.BinaryMarshaler = (*QueuesCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*QueuesCounter)(nil)

func (m *QueuesCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *QueuesCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// QueuesGarbageCollectionRecord

var _ encoding.BinaryMarshaler = (*QueuesGarbageCollectionRecord)(nil)
var _ encoding.BinaryUnmarshaler = (*QueuesGarbageCollectionRecord)(nil)

func (m *QueuesGarbageCollectionRecord) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *QueuesGarbageCollectionRecord) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RateLimiterState

var _ encoding.BinaryMarshaler = (*RateLimiterState)(nil)
var _ encoding.BinaryUnmarshaler = (*RateLimiterState)(nil)

func (m *RateLimiterState) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RateLimiterState) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReportSchedulesStatusRequest

var _ encoding.BinaryMarshaler = (*ReportSchedulesStatusRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ReportSchedulesStatusRequest)(nil)

func (m *ReportSchedulesStatusRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReportSchedulesStatusRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReportSchedulesStatusResponse

var _ encoding.BinaryMarshaler = (*ReportSchedulesStatusResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ReportSchedulesStatusResponse)(nil)

func (m *ReportSchedulesStatusResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReportSchedulesStatusResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReportStatusRequest

var _ encoding.BinaryMarshaler = (*ReportStatusRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*ReportStatusRequest)(nil)

func (m *ReportStatusRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReportStatusRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReportStatusRequestEntry

var _ encoding.BinaryMarshaler = (*ReportStatusRequestEntry)(nil)
var _ encoding.BinaryUnmarshaler = (*ReportStatusRequestEntry)(nil)

func (m *ReportStatusRequestEntry) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReportStatusRequestEntry) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ReportStatusResponse

var _ encoding.BinaryMarshaler = (*ReportStatusResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*ReportStatusResponse)(nil)

func (m *ReportStatusResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ReportStatusResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RestartTasksRequest

var _ encoding.BinaryMarshaler = (*RestartTasksRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RestartTasksRequest)(nil)

func (m *RestartTasksRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RestartTasksRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RestartTasksRequestEntry

var _ encoding.BinaryMarshaler = (*RestartTasksRequestEntry)(nil)
var _ encoding.BinaryUnmarshaler = (*RestartTasksRequestEntry)(nil)

func (m *RestartTasksRequestEntry) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RestartTasksRequestEntry) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RestartTasksResponse

var _ encoding.BinaryMarshaler = (*RestartTasksResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RestartTasksResponse)(nil)

func (m *RestartTasksResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RestartTasksResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RestartTasksResponseEntry

var _ encoding.BinaryMarshaler = (*RestartTasksResponseEntry)(nil)
var _ encoding.BinaryUnmarshaler = (*RestartTasksResponseEntry)(nil)

func (m *RestartTasksResponseEntry) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RestartTasksResponseEntry) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RetryStrategy

var _ encoding.BinaryMarshaler = (*RetryStrategy)(nil)
var _ encoding.BinaryUnmarshaler = (*RetryStrategy)(nil)

func (m *RetryStrategy) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RetryStrategy) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunQueuesGarbageCollectionRequest

var _ encoding.BinaryMarshaler = (*RunQueuesGarbageCollectionRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RunQueuesGarbageCollectionRequest)(nil)

func (m *RunQueuesGarbageCollectionRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunQueuesGarbageCollectionRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunQueuesGarbageCollectionResponse

var _ encoding.BinaryMarshaler = (*RunQueuesGarbageCollectionResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RunQueuesGarbageCollectionResponse)(nil)

func (m *RunQueuesGarbageCollectionResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunQueuesGarbageCollectionResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunTasksGarbageCollectionRequest

var _ encoding.BinaryMarshaler = (*RunTasksGarbageCollectionRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*RunTasksGarbageCollectionRequest)(nil)

func (m *RunTasksGarbageCollectionRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunTasksGarbageCollectionRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// RunTasksGarbageCollectionResponse

var _ encoding.BinaryMarshaler = (*RunTasksGarbageCollectionResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*RunTasksGarbageCollectionResponse)(nil)

func (m *RunTasksGarbageCollectionResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *RunTasksGarbageCollectionResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Schedule

var _ encoding.BinaryMarshaler = (*Schedule)(nil)
var _ encoding.BinaryUnmarshaler = (*Schedule)(nil)

func (m *Schedule) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Schedule) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// ScheduleId

var _ encoding.BinaryMarshaler = (*ScheduleId)(nil)
var _ encoding.BinaryUnmarshaler = (*ScheduleId)(nil)

func (m *ScheduleId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *ScheduleId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Task

var _ encoding.BinaryMarshaler = (*Task)(nil)
var _ encoding.BinaryUnmarshaler = (*Task)(nil)

func (m *Task) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Task) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// TaskId

var _ encoding.BinaryMarshaler = (*TaskId)(nil)
var _ encoding.BinaryUnmarshaler = (*TaskId)(nil)

func (m *TaskId) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *TaskId) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// TasksCounter

var _ encoding.BinaryMarshaler = (*TasksCounter)(nil)
var _ encoding.BinaryUnmarshaler = (*TasksCounter)(nil)

func (m *TasksCounter) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *TasksCounter) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// Thread

var _ encoding.BinaryMarshaler = (*Thread)(nil)
var _ encoding.BinaryUnmarshaler = (*Thread)(nil)

func (m *Thread) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *Thread) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// TokenBucketRateLimiting

var _ encoding.BinaryMarshaler = (*TokenBucketRateLimiting)(nil)
var _ encoding.BinaryUnmarshaler = (*TokenBucketRateLimiting)(nil)

func (m *TokenBucketRateLimiting) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *TokenBucketRateLimiting) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateQueueRequest

var _ encoding.BinaryMarshaler = (*UpdateQueueRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateQueueRequest)(nil)

func (m *UpdateQueueRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateQueueRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateQueueResponse

var _ encoding.BinaryMarshaler = (*UpdateQueueResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateQueueResponse)(nil)

func (m *UpdateQueueResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateQueueResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateScheduleRequest

var _ encoding.BinaryMarshaler = (*UpdateScheduleRequest)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateScheduleRequest)(nil)

func (m *UpdateScheduleRequest) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateScheduleRequest) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}

// UpdateScheduleResponse

var _ encoding.BinaryMarshaler = (*UpdateScheduleResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*UpdateScheduleResponse)(nil)

func (m *UpdateScheduleResponse) UnmarshalBinary(data []byte) error {
	return m.UnmarshalVT(data)
}

func (m *UpdateScheduleResponse) MarshalBinary() (data []byte, err error) {
	return m.MarshalVT()
}
