// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: pkg/corepb/queues.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntervalUnit int32

const (
	IntervalUnit_INTERVAL_UNIT_INVALID IntervalUnit = 0
	IntervalUnit_INTERVAL_UNIT_SECONDS IntervalUnit = 1
	IntervalUnit_INTERVAL_UNIT_MINUTES IntervalUnit = 2
	IntervalUnit_INTERVAL_UNIT_HOURS   IntervalUnit = 3
)

// Enum value maps for IntervalUnit.
var (
	IntervalUnit_name = map[int32]string{
		0: "INTERVAL_UNIT_INVALID",
		1: "INTERVAL_UNIT_SECONDS",
		2: "INTERVAL_UNIT_MINUTES",
		3: "INTERVAL_UNIT_HOURS",
	}
	IntervalUnit_value = map[string]int32{
		"INTERVAL_UNIT_INVALID": 0,
		"INTERVAL_UNIT_SECONDS": 1,
		"INTERVAL_UNIT_MINUTES": 2,
		"INTERVAL_UNIT_HOURS":   3,
	}
)

func (x IntervalUnit) Enum() *IntervalUnit {
	p := new(IntervalUnit)
	*p = x
	return p
}

func (x IntervalUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntervalUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_queues_proto_enumTypes[0].Descriptor()
}

func (IntervalUnit) Type() protoreflect.EnumType {
	return &file_pkg_corepb_queues_proto_enumTypes[0]
}

func (x IntervalUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntervalUnit.Descriptor instead.
func (IntervalUnit) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{0}
}

type Queue struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *QueueId               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   int64                  `protobuf:"fixed64,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   int64                  `protobuf:"fixed64,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version     int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	// Defaults on queue level, overrides on task level
	KeepaliveTimeoutInSeconds int64                  `protobuf:"varint,7,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy         `protobuf:"bytes,8,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	DequeuingSettings         *DequeuingSettings     `protobuf:"bytes,9,opt,name=dequeuing_settings,json=dequeuingSettings,proto3" json:"dequeuing_settings,omitempty"`
	DeadLetterQueueConfig     *DeadLetterQueueConfig `protobuf:"bytes,10,opt,name=dead_letter_queue_config,json=deadLetterQueueConfig,proto3" json:"dead_letter_queue_config,omitempty"`
	ExpiresInSeconds          int64                  `protobuf:"varint,11,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	// Denormalized count of schedules belonging to this queue, maintained by
	// CreateSchedule/DeleteSchedule. Used instead of a separate counter entity
	// to bound the number of schedules per queue and to report schedule counts
	// without an O(n) scan over the schedules table.
	SchedulesCount int64 `protobuf:"varint,12,opt,name=schedules_count,json=schedulesCount,proto3" json:"schedules_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{0}
}

func (x *Queue) GetId() *QueueId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Queue) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Queue) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Queue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Queue) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *Queue) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *Queue) GetDequeuingSettings() *DequeuingSettings {
	if x != nil {
		return x.DequeuingSettings
	}
	return nil
}

func (x *Queue) GetDeadLetterQueueConfig() *DeadLetterQueueConfig {
	if x != nil {
		return x.DeadLetterQueueConfig
	}
	return nil
}

func (x *Queue) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *Queue) GetSchedulesCount() int64 {
	if x != nil {
		return x.SchedulesCount
	}
	return 0
}

type QueueId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueId       uint64                 `protobuf:"fixed64,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueId) Reset() {
	*x = QueueId{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueId) ProtoMessage() {}

func (x *QueueId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueId.ProtoReflect.Descriptor instead.
func (*QueueId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{1}
}

func (x *QueueId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *QueueId) GetQueueId() uint64 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

type DeadLetterQueueConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enable  bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	MaxSize int64                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"` // 0 - unlimited
	// Required whenever this message is set, regardless of enable; bounded to
	// [minExpiresTimeoutInSeconds, maxDLQRetentionPeriod] in validators.go — no
	// "unlimited" sentinel, every dead task always has a real retention deadline.
	RetentionPeriodInSeconds int64 `protobuf:"varint,3,opt,name=retention_period_in_seconds,json=retentionPeriodInSeconds,proto3" json:"retention_period_in_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeadLetterQueueConfig) Reset() {
	*x = DeadLetterQueueConfig{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetterQueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetterQueueConfig) ProtoMessage() {}

func (x *DeadLetterQueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetterQueueConfig.ProtoReflect.Descriptor instead.
func (*DeadLetterQueueConfig) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{2}
}

func (x *DeadLetterQueueConfig) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *DeadLetterQueueConfig) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *DeadLetterQueueConfig) GetRetentionPeriodInSeconds() int64 {
	if x != nil {
		return x.RetentionPeriodInSeconds
	}
	return 0
}

type DequeuingSettings struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	MaxInProgressTasks int64                    `protobuf:"varint,1,opt,name=max_in_progress_tasks,json=maxInProgressTasks,proto3" json:"max_in_progress_tasks,omitempty"`
	RateLimiting       *TokenBucketRateLimiting `protobuf:"bytes,2,opt,name=rate_limiting,json=rateLimiting,proto3" json:"rate_limiting,omitempty"`
	DequeuingPaused    bool                     `protobuf:"varint,3,opt,name=dequeuing_paused,json=dequeuingPaused,proto3" json:"dequeuing_paused,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DequeuingSettings) Reset() {
	*x = DequeuingSettings{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeuingSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeuingSettings) ProtoMessage() {}

func (x *DequeuingSettings) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeuingSettings.ProtoReflect.Descriptor instead.
func (*DequeuingSettings) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{3}
}

func (x *DequeuingSettings) GetMaxInProgressTasks() int64 {
	if x != nil {
		return x.MaxInProgressTasks
	}
	return 0
}

func (x *DequeuingSettings) GetRateLimiting() *TokenBucketRateLimiting {
	if x != nil {
		return x.RateLimiting
	}
	return nil
}

func (x *DequeuingSettings) GetDequeuingPaused() bool {
	if x != nil {
		return x.DequeuingPaused
	}
	return false
}

type TokenBucketRateLimiting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens     int64                  `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Interval      int64                  `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	IntervalUnit  IntervalUnit           `protobuf:"varint,3,opt,name=interval_unit,json=intervalUnit,proto3,enum=com.evrblk.moab.corepb.IntervalUnit" json:"interval_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBucketRateLimiting) Reset() {
	*x = TokenBucketRateLimiting{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBucketRateLimiting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBucketRateLimiting) ProtoMessage() {}

func (x *TokenBucketRateLimiting) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBucketRateLimiting.ProtoReflect.Descriptor instead.
func (*TokenBucketRateLimiting) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{4}
}

func (x *TokenBucketRateLimiting) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *TokenBucketRateLimiting) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *TokenBucketRateLimiting) GetIntervalUnit() IntervalUnit {
	if x != nil {
		return x.IntervalUnit
	}
	return IntervalUnit_INTERVAL_UNIT_INVALID
}

type Schedule struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *ScheduleId            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   int64                  `protobuf:"fixed64,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   int64                  `protobuf:"fixed64,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version     int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Cron        string                 `protobuf:"bytes,7,opt,name=cron,proto3" json:"cron,omitempty"`
	Payload     []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	DedupeKey   string                 `protobuf:"bytes,9,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`
	// Override for expiration set on the queue. 0 - no override.
	ExpiresInSeconds          int64          `protobuf:"varint,10,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	KeepaliveTimeoutInSeconds int64          `protobuf:"varint,11,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy `protobuf:"bytes,12,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	// Timezone at which to work with cron schedule
	Timezone string `protobuf:"bytes,13,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Last time CronTasker checked on this schedule
	LastCheckedAt int64 `protobuf:"fixed64,14,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	// Next earliest cron tick which is scheduled, but not enqueued yet
	NextScheduledAt int64 `protobuf:"fixed64,15,opt,name=next_scheduled_at,json=nextScheduledAt,proto3" json:"next_scheduled_at,omitempty"`
	LastEnqueuedFor int64 `protobuf:"fixed64,16,opt,name=last_enqueued_for,json=lastEnqueuedFor,proto3" json:"last_enqueued_for,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{5}
}

func (x *Schedule) GetId() *ScheduleId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Schedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schedule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schedule) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Schedule) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Schedule) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Schedule) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Schedule) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Schedule) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *Schedule) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *Schedule) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *Schedule) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *Schedule) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Schedule) GetLastCheckedAt() int64 {
	if x != nil {
		return x.LastCheckedAt
	}
	return 0
}

func (x *Schedule) GetNextScheduledAt() int64 {
	if x != nil {
		return x.NextScheduledAt
	}
	return 0
}

func (x *Schedule) GetLastEnqueuedFor() int64 {
	if x != nil {
		return x.LastEnqueuedFor
	}
	return 0
}

type ScheduleId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueId       uint64                 `protobuf:"fixed64,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	ScheduleId    uint64                 `protobuf:"fixed64,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleId) Reset() {
	*x = ScheduleId{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleId) ProtoMessage() {}

func (x *ScheduleId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleId.ProtoReflect.Descriptor instead.
func (*ScheduleId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ScheduleId) GetQueueId() uint64 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *ScheduleId) GetScheduleId() uint64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

type CreateQueueRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	QueueId                   *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description               string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	KeepaliveTimeoutInSeconds int64                  `protobuf:"varint,4,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy         `protobuf:"bytes,5,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	DequeuingSettings         *DequeuingSettings     `protobuf:"bytes,6,opt,name=dequeuing_settings,json=dequeuingSettings,proto3" json:"dequeuing_settings,omitempty"`
	DeadLetterQueueConfig     *DeadLetterQueueConfig `protobuf:"bytes,7,opt,name=dead_letter_queue_config,json=deadLetterQueueConfig,proto3" json:"dead_letter_queue_config,omitempty"`
	ExpiresInSeconds          int64                  `protobuf:"varint,8,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	MaxNumberOfQueues         int64                  `protobuf:"varint,9,opt,name=max_number_of_queues,json=maxNumberOfQueues,proto3" json:"max_number_of_queues,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{7}
}

func (x *CreateQueueRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *CreateQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQueueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateQueueRequest) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *CreateQueueRequest) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *CreateQueueRequest) GetDequeuingSettings() *DequeuingSettings {
	if x != nil {
		return x.DequeuingSettings
	}
	return nil
}

func (x *CreateQueueRequest) GetDeadLetterQueueConfig() *DeadLetterQueueConfig {
	if x != nil {
		return x.DeadLetterQueueConfig
	}
	return nil
}

func (x *CreateQueueRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *CreateQueueRequest) GetMaxNumberOfQueues() int64 {
	if x != nil {
		return x.MaxNumberOfQueues
	}
	return 0
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{8}
}

func (x *CreateQueueResponse) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{9}
}

func (x *GetQueueRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

type GetQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{10}
}

func (x *GetQueueResponse) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type GetQueueByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueByNameRequest) Reset() {
	*x = GetQueueByNameRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueByNameRequest) ProtoMessage() {}

func (x *GetQueueByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueByNameRequest.ProtoReflect.Descriptor instead.
func (*GetQueueByNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{11}
}

func (x *GetQueueByNameRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetQueueByNameRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type GetQueueByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueByNameResponse) Reset() {
	*x = GetQueueByNameResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueByNameResponse) ProtoMessage() {}

func (x *GetQueueByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueByNameResponse.ProtoReflect.Descriptor instead.
func (*GetQueueByNameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{12}
}

func (x *GetQueueByNameResponse) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type UpdateQueueRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AccountId                 uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName                 string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Description               string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	KeepaliveTimeoutInSeconds int64                  `protobuf:"varint,4,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy         `protobuf:"bytes,5,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	DequeuingSettings         *DequeuingSettings     `protobuf:"bytes,6,opt,name=dequeuing_settings,json=dequeuingSettings,proto3" json:"dequeuing_settings,omitempty"`
	DeadLetterQueueConfig     *DeadLetterQueueConfig `protobuf:"bytes,7,opt,name=dead_letter_queue_config,json=deadLetterQueueConfig,proto3" json:"dead_letter_queue_config,omitempty"`
	ExpiresInSeconds          int64                  `protobuf:"varint,8,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	// Optimistic concurrency check: must equal the queue's current version or
	// the update is rejected.
	ExpectedVersion int64 `protobuf:"varint,9,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateQueueRequest) Reset() {
	*x = UpdateQueueRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQueueRequest) ProtoMessage() {}

func (x *UpdateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQueueRequest.ProtoReflect.Descriptor instead.
func (*UpdateQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateQueueRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *UpdateQueueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateQueueRequest) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *UpdateQueueRequest) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *UpdateQueueRequest) GetDequeuingSettings() *DequeuingSettings {
	if x != nil {
		return x.DequeuingSettings
	}
	return nil
}

func (x *UpdateQueueRequest) GetDeadLetterQueueConfig() *DeadLetterQueueConfig {
	if x != nil {
		return x.DeadLetterQueueConfig
	}
	return nil
}

func (x *UpdateQueueRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *UpdateQueueRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type UpdateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQueueResponse) Reset() {
	*x = UpdateQueueResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQueueResponse) ProtoMessage() {}

func (x *UpdateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQueueResponse.ProtoReflect.Descriptor instead.
func (*UpdateQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateQueueResponse) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteQueueRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type DeleteQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueResponse) Reset() {
	*x = DeleteQueueResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueResponse) ProtoMessage() {}

func (x *DeleteQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{16}
}

type ListQueuesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{17}
}

func (x *ListQueuesRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ListQueuesRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListQueuesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListQueuesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Queues                  []*Queue               `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{18}
}

func (x *ListQueuesResponse) GetQueues() []*Queue {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *ListQueuesResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListQueuesResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type CreateScheduleRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AccountId                    uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName                    string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ScheduleId                   uint64                 `protobuf:"fixed64,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	ScheduleName                 string                 `protobuf:"bytes,4,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	Description                  string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Cron                         string                 `protobuf:"bytes,6,opt,name=cron,proto3" json:"cron,omitempty"`
	Payload                      []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	DedupeKey                    string                 `protobuf:"bytes,8,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`
	ExpiresInSeconds             int64                  `protobuf:"varint,9,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	KeepaliveTimeoutInSeconds    int64                  `protobuf:"varint,10,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy                *RetryStrategy         `protobuf:"bytes,11,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	Timezone                     string                 `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`
	MaxNumberOfSchedulesPerQueue int64                  `protobuf:"varint,13,opt,name=max_number_of_schedules_per_queue,json=maxNumberOfSchedulesPerQueue,proto3" json:"max_number_of_schedules_per_queue,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{19}
}

func (x *CreateScheduleRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateScheduleRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CreateScheduleRequest) GetScheduleId() uint64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

func (x *CreateScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *CreateScheduleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduleRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CreateScheduleRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateScheduleRequest) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *CreateScheduleRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *CreateScheduleRequest) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *CreateScheduleRequest) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *CreateScheduleRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateScheduleRequest) GetMaxNumberOfSchedulesPerQueue() int64 {
	if x != nil {
		return x.MaxNumberOfSchedulesPerQueue
	}
	return 0
}

type CreateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleResponse) Reset() {
	*x = CreateScheduleResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleResponse) ProtoMessage() {}

func (x *CreateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{20}
}

func (x *CreateScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ScheduleName  string                 `protobuf:"bytes,3,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{21}
}

func (x *GetScheduleRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetScheduleRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *GetScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{22}
}

func (x *GetScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type ListSchedulesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QueueId         *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{23}
}

func (x *ListSchedulesRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *ListSchedulesRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListSchedulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSchedulesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Schedules               []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{24}
}

func (x *ListSchedulesResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *ListSchedulesResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListSchedulesResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type UpdateScheduleRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AccountId                 uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName                 string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ScheduleName              string                 `protobuf:"bytes,3,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	Description               string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cron                      string                 `protobuf:"bytes,5,opt,name=cron,proto3" json:"cron,omitempty"`
	Payload                   []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	DedupeKey                 string                 `protobuf:"bytes,7,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`
	ExpiresInSeconds          int64                  `protobuf:"varint,8,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	KeepaliveTimeoutInSeconds int64                  `protobuf:"varint,9,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy         `protobuf:"bytes,10,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	Timezone                  string                 `protobuf:"bytes,11,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Optimistic concurrency check: must equal the schedule's current version or
	// the update is rejected.
	ExpectedVersion int64 `protobuf:"varint,12,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateScheduleRequest) Reset() {
	*x = UpdateScheduleRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleRequest) ProtoMessage() {}

func (x *UpdateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateScheduleRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateScheduleRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *UpdateScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *UpdateScheduleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScheduleRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *UpdateScheduleRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateScheduleRequest) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *UpdateScheduleRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *UpdateScheduleRequest) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *UpdateScheduleRequest) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *UpdateScheduleRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateScheduleRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type UpdateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleResponse) Reset() {
	*x = UpdateScheduleResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleResponse) ProtoMessage() {}

func (x *UpdateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleResponse.ProtoReflect.Descriptor instead.
func (*UpdateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ScheduleName  string                 `protobuf:"bytes,3,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteScheduleRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteScheduleRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DeleteScheduleRequest) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

type DeleteScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleResponse) Reset() {
	*x = DeleteScheduleResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleResponse) ProtoMessage() {}

func (x *DeleteScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{28}
}

type DequeSchedulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute UnixNano timestamp
	DueBefore     int64 `protobuf:"varint,1,opt,name=due_before,json=dueBefore,proto3" json:"due_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeSchedulesRequest) Reset() {
	*x = DequeSchedulesRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeSchedulesRequest) ProtoMessage() {}

func (x *DequeSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeSchedulesRequest.ProtoReflect.Descriptor instead.
func (*DequeSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{29}
}

func (x *DequeSchedulesRequest) GetDueBefore() int64 {
	if x != nil {
		return x.DueBefore
	}
	return 0
}

type DequeSchedulesResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Entries       []*DequeSchedulesResponseEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeSchedulesResponse) Reset() {
	*x = DequeSchedulesResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeSchedulesResponse) ProtoMessage() {}

func (x *DequeSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeSchedulesResponse.ProtoReflect.Descriptor instead.
func (*DequeSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{30}
}

func (x *DequeSchedulesResponse) GetEntries() []*DequeSchedulesResponseEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DequeSchedulesResponseEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Queue         *Queue                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeSchedulesResponseEntry) Reset() {
	*x = DequeSchedulesResponseEntry{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeSchedulesResponseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeSchedulesResponseEntry) ProtoMessage() {}

func (x *DequeSchedulesResponseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeSchedulesResponseEntry.ProtoReflect.Descriptor instead.
func (*DequeSchedulesResponseEntry) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{31}
}

func (x *DequeSchedulesResponseEntry) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *DequeSchedulesResponseEntry) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type ReportSchedulesStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId      *ScheduleId            `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	NextScheduledAt int64                  `protobuf:"fixed64,2,opt,name=next_scheduled_at,json=nextScheduledAt,proto3" json:"next_scheduled_at,omitempty"`
	// The greatest ScheduledAt among the tasks the worker actually enqueued
	// for this schedule during this tick, or 0 if none were enqueued (in which
	// case the previously stored value is left untouched). Together with
	// Schedule.last_checked_at (set from this request's own Now, not a
	// separate field), identifies the time range for which tasks should have
	// been (but may not have been) scheduled: (previous last_enqueued_for,
	// due_before] as of last_checked_at.
	LastEnqueuedFor int64 `protobuf:"fixed64,3,opt,name=last_enqueued_for,json=lastEnqueuedFor,proto3" json:"last_enqueued_for,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportSchedulesStatusRequest) Reset() {
	*x = ReportSchedulesStatusRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSchedulesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSchedulesStatusRequest) ProtoMessage() {}

func (x *ReportSchedulesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSchedulesStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportSchedulesStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{32}
}

func (x *ReportSchedulesStatusRequest) GetScheduleId() *ScheduleId {
	if x != nil {
		return x.ScheduleId
	}
	return nil
}

func (x *ReportSchedulesStatusRequest) GetNextScheduledAt() int64 {
	if x != nil {
		return x.NextScheduledAt
	}
	return 0
}

func (x *ReportSchedulesStatusRequest) GetLastEnqueuedFor() int64 {
	if x != nil {
		return x.LastEnqueuedFor
	}
	return 0
}

type ReportSchedulesStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSchedulesStatusResponse) Reset() {
	*x = ReportSchedulesStatusResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSchedulesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSchedulesStatusResponse) ProtoMessage() {}

func (x *ReportSchedulesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSchedulesStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportSchedulesStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{33}
}

type QueuesCounter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NumberOfQueues int64                  `protobuf:"varint,1,opt,name=number_of_queues,json=numberOfQueues,proto3" json:"number_of_queues,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueuesCounter) Reset() {
	*x = QueuesCounter{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuesCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesCounter) ProtoMessage() {}

func (x *QueuesCounter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesCounter.ProtoReflect.Descriptor instead.
func (*QueuesCounter) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{34}
}

func (x *QueuesCounter) GetNumberOfQueues() int64 {
	if x != nil {
		return x.NumberOfQueues
	}
	return 0
}

// QueuesGarbageCollectionRecord is an internal bookkeeping entry queuing a
// deleted queue's schedules for asynchronous deletion. DeleteQueue creates
// one of these instead of deleting the queue's schedules synchronously;
// RunQueuesGarbageCollection drains them in bounded batches.
type QueuesGarbageCollectionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuesGarbageCollectionRecord) Reset() {
	*x = QueuesGarbageCollectionRecord{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuesGarbageCollectionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesGarbageCollectionRecord) ProtoMessage() {}

func (x *QueuesGarbageCollectionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesGarbageCollectionRecord.ProtoReflect.Descriptor instead.
func (*QueuesGarbageCollectionRecord) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{35}
}

func (x *QueuesGarbageCollectionRecord) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

type RunQueuesGarbageCollectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many pending GC records (deleted queues) to process in this call.
	GcRecordsPageSize int32 `protobuf:"varint,1,opt,name=gc_records_page_size,json=gcRecordsPageSize,proto3" json:"gc_records_page_size,omitempty"`
	// How many schedules to delete per GC record in this call.
	GcRecordSchedulesPageSize int32 `protobuf:"varint,2,opt,name=gc_record_schedules_page_size,json=gcRecordSchedulesPageSize,proto3" json:"gc_record_schedules_page_size,omitempty"`
	// Total schedule deletions allowed across all GC records in this call.
	MaxVisitedSchedules int32 `protobuf:"varint,3,opt,name=max_visited_schedules,json=maxVisitedSchedules,proto3" json:"max_visited_schedules,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunQueuesGarbageCollectionRequest) Reset() {
	*x = RunQueuesGarbageCollectionRequest{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunQueuesGarbageCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunQueuesGarbageCollectionRequest) ProtoMessage() {}

func (x *RunQueuesGarbageCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunQueuesGarbageCollectionRequest.ProtoReflect.Descriptor instead.
func (*RunQueuesGarbageCollectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{36}
}

func (x *RunQueuesGarbageCollectionRequest) GetGcRecordsPageSize() int32 {
	if x != nil {
		return x.GcRecordsPageSize
	}
	return 0
}

func (x *RunQueuesGarbageCollectionRequest) GetGcRecordSchedulesPageSize() int32 {
	if x != nil {
		return x.GcRecordSchedulesPageSize
	}
	return 0
}

func (x *RunQueuesGarbageCollectionRequest) GetMaxVisitedSchedules() int32 {
	if x != nil {
		return x.MaxVisitedSchedules
	}
	return 0
}

type RunQueuesGarbageCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunQueuesGarbageCollectionResponse) Reset() {
	*x = RunQueuesGarbageCollectionResponse{}
	mi := &file_pkg_corepb_queues_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunQueuesGarbageCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunQueuesGarbageCollectionResponse) ProtoMessage() {}

func (x *RunQueuesGarbageCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_queues_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunQueuesGarbageCollectionResponse.ProtoReflect.Descriptor instead.
func (*RunQueuesGarbageCollectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_queues_proto_rawDescGZIP(), []int{37}
}

var File_pkg_corepb_queues_proto protoreflect.FileDescriptor

const file_pkg_corepb_queues_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/corepb/queues.proto\x12\x16com.evrblk.moab.corepb\x1a\x17pkg/corepb/common.proto\"\xee\x04\n" +
	"\x05Queue\x12/\n" +
	"\x02id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x10R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x10R\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\a \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\b \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12X\n" +
	"\x12dequeuing_settings\x18\t \x01(\v2).com.evrblk.moab.corepb.DequeuingSettingsR\x11dequeuingSettings\x12f\n" +
	"\x18dead_letter_queue_config\x18\n" +
	" \x01(\v2-.com.evrblk.moab.corepb.DeadLetterQueueConfigR\x15deadLetterQueueConfig\x12,\n" +
	"\x12expires_in_seconds\x18\v \x01(\x03R\x10expiresInSeconds\x12'\n" +
	"\x0fschedules_count\x18\f \x01(\x03R\x0eschedulesCount\"C\n" +
	"\aQueueId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\x06R\aqueueId\"\x89\x01\n" +
	"\x15DeadLetterQueueConfig\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x03R\amaxSize\x12=\n" +
	"\x1bretention_period_in_seconds\x18\x03 \x01(\x03R\x18retentionPeriodInSeconds\"\xc7\x01\n" +
	"\x11DequeuingSettings\x121\n" +
	"\x15max_in_progress_tasks\x18\x01 \x01(\x03R\x12maxInProgressTasks\x12T\n" +
	"\rrate_limiting\x18\x02 \x01(\v2/.com.evrblk.moab.corepb.TokenBucketRateLimitingR\frateLimiting\x12)\n" +
	"\x10dequeuing_paused\x18\x03 \x01(\bR\x0fdequeuingPaused\"\x9f\x01\n" +
	"\x17TokenBucketRateLimiting\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x03R\tmaxTokens\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x03R\binterval\x12I\n" +
	"\rinterval_unit\x18\x03 \x01(\x0e2$.com.evrblk.moab.corepb.IntervalUnitR\fintervalUnit\"\xf2\x04\n" +
	"\bSchedule\x122\n" +
	"\x02id\x18\x01 \x01(\v2\".com.evrblk.moab.corepb.ScheduleIdR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x10R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x10R\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x12\n" +
	"\x04cron\x18\a \x01(\tR\x04cron\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\t \x01(\tR\tdedupeKey\x12,\n" +
	"\x12expires_in_seconds\x18\n" +
	" \x01(\x03R\x10expiresInSeconds\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\v \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\f \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12\x1a\n" +
	"\btimezone\x18\r \x01(\tR\btimezone\x12&\n" +
	"\x0flast_checked_at\x18\x0e \x01(\x10R\rlastCheckedAt\x12*\n" +
	"\x11next_scheduled_at\x18\x0f \x01(\x10R\x0fnextScheduledAt\x12*\n" +
	"\x11last_enqueued_for\x18\x10 \x01(\x10R\x0flastEnqueuedFor\"g\n" +
	"\n" +
	"ScheduleId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\x06R\aqueueId\x12\x1f\n" +
	"\vschedule_id\x18\x03 \x01(\x06R\n" +
	"scheduleId\"\xb6\x04\n" +
	"\x12CreateQueueRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\x04 \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\x05 \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12X\n" +
	"\x12dequeuing_settings\x18\x06 \x01(\v2).com.evrblk.moab.corepb.DequeuingSettingsR\x11dequeuingSettings\x12f\n" +
	"\x18dead_letter_queue_config\x18\a \x01(\v2-.com.evrblk.moab.corepb.DeadLetterQueueConfigR\x15deadLetterQueueConfig\x12,\n" +
	"\x12expires_in_seconds\x18\b \x01(\x03R\x10expiresInSeconds\x12/\n" +
	"\x14max_number_of_queues\x18\t \x01(\x03R\x11maxNumberOfQueues\"J\n" +
	"\x13CreateQueueResponse\x123\n" +
	"\x05queue\x18\x01 \x01(\v2\x1d.com.evrblk.moab.corepb.QueueR\x05queue\"M\n" +
	"\x0fGetQueueRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\"G\n" +
	"\x10GetQueueResponse\x123\n" +
	"\x05queue\x18\x01 \x01(\v2\x1d.com.evrblk.moab.corepb.QueueR\x05queue\"U\n" +
	"\x15GetQueueByNameRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"M\n" +
	"\x16GetQueueByNameResponse\x123\n" +
	"\x05queue\x18\x01 \x01(\v2\x1d.com.evrblk.moab.corepb.QueueR\x05queue\"\x9e\x04\n" +
	"\x12UpdateQueueRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\x04 \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\x05 \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12X\n" +
	"\x12dequeuing_settings\x18\x06 \x01(\v2).com.evrblk.moab.corepb.DequeuingSettingsR\x11dequeuingSettings\x12f\n" +
	"\x18dead_letter_queue_config\x18\a \x01(\v2-.com.evrblk.moab.corepb.DeadLetterQueueConfigR\x15deadLetterQueueConfig\x12,\n" +
	"\x12expires_in_seconds\x18\b \x01(\x03R\x10expiresInSeconds\x12)\n" +
	"\x10expected_version\x18\t \x01(\x03R\x0fexpectedVersion\"J\n" +
	"\x13UpdateQueueResponse\x123\n" +
	"\x05queue\x18\x01 \x01(\v2\x1d.com.evrblk.moab.corepb.QueueR\x05queue\"R\n" +
	"\x12DeleteQueueRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"\x15\n" +
	"\x13DeleteQueueResponse\"\x9c\x01\n" +
	"\x11ListQueuesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12R\n" +
	"\x10pagination_token\x18\x02 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8d\x02\n" +
	"\x12ListQueuesResponse\x125\n" +
	"\x06queues\x18\x01 \x03(\v2\x1d.com.evrblk.moab.corepb.QueueR\x06queues\x12[\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x13nextPaginationToken\x12c\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x17previousPaginationToken\"\xac\x04\n" +
	"\x15CreateScheduleRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vschedule_id\x18\x03 \x01(\x06R\n" +
	"scheduleId\x12#\n" +
	"\rschedule_name\x18\x04 \x01(\tR\fscheduleName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cron\x18\x06 \x01(\tR\x04cron\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\b \x01(\tR\tdedupeKey\x12,\n" +
	"\x12expires_in_seconds\x18\t \x01(\x03R\x10expiresInSeconds\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\n" +
	" \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\v \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12\x1a\n" +
	"\btimezone\x18\f \x01(\tR\btimezone\x12G\n" +
	"!max_number_of_schedules_per_queue\x18\r \x01(\x03R\x1cmaxNumberOfSchedulesPerQueue\"V\n" +
	"\x16CreateScheduleResponse\x12<\n" +
	"\bschedule\x18\x01 \x01(\v2 .com.evrblk.moab.corepb.ScheduleR\bschedule\"w\n" +
	"\x12GetScheduleRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12#\n" +
	"\rschedule_name\x18\x03 \x01(\tR\fscheduleName\"S\n" +
	"\x13GetScheduleResponse\x12<\n" +
	"\bschedule\x18\x01 \x01(\v2 .com.evrblk.moab.corepb.ScheduleR\bschedule\"\xbc\x01\n" +
	"\x14ListSchedulesRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12R\n" +
	"\x10pagination_token\x18\x02 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x99\x02\n" +
	"\x15ListSchedulesResponse\x12>\n" +
	"\tschedules\x18\x01 \x03(\v2 .com.evrblk.moab.corepb.ScheduleR\tschedules\x12[\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x13nextPaginationToken\x12c\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x17previousPaginationToken\"\xed\x03\n" +
	"\x15UpdateScheduleRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12#\n" +
	"\rschedule_name\x18\x03 \x01(\tR\fscheduleName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cron\x18\x05 \x01(\tR\x04cron\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\a \x01(\tR\tdedupeKey\x12,\n" +
	"\x12expires_in_seconds\x18\b \x01(\x03R\x10expiresInSeconds\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\t \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\n" +
	" \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12\x1a\n" +
	"\btimezone\x18\v \x01(\tR\btimezone\x12)\n" +
	"\x10expected_version\x18\f \x01(\x03R\x0fexpectedVersion\"V\n" +
	"\x16UpdateScheduleResponse\x12<\n" +
	"\bschedule\x18\x01 \x01(\v2 .com.evrblk.moab.corepb.ScheduleR\bschedule\"z\n" +
	"\x15DeleteScheduleRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12#\n" +
	"\rschedule_name\x18\x03 \x01(\tR\fscheduleName\"\x18\n" +
	"\x16DeleteScheduleResponse\"6\n" +
	"\x15DequeSchedulesRequest\x12\x1d\n" +
	"\n" +
	"due_before\x18\x01 \x01(\x03R\tdueBefore\"g\n" +
	"\x16DequeSchedulesResponse\x12M\n" +
	"\aentries\x18\x01 \x03(\v23.com.evrblk.moab.corepb.DequeSchedulesResponseEntryR\aentries\"\x90\x01\n" +
	"\x1bDequeSchedulesResponseEntry\x12<\n" +
	"\bschedule\x18\x01 \x01(\v2 .com.evrblk.moab.corepb.ScheduleR\bschedule\x123\n" +
	"\x05queue\x18\x02 \x01(\v2\x1d.com.evrblk.moab.corepb.QueueR\x05queue\"\xbb\x01\n" +
	"\x1cReportSchedulesStatusRequest\x12C\n" +
	"\vschedule_id\x18\x01 \x01(\v2\".com.evrblk.moab.corepb.ScheduleIdR\n" +
	"scheduleId\x12*\n" +
	"\x11next_scheduled_at\x18\x02 \x01(\x10R\x0fnextScheduledAt\x12*\n" +
	"\x11last_enqueued_for\x18\x03 \x01(\x10R\x0flastEnqueuedFor\"\x1f\n" +
	"\x1dReportSchedulesStatusResponse\"9\n" +
	"\rQueuesCounter\x12(\n" +
	"\x10number_of_queues\x18\x01 \x01(\x03R\x0enumberOfQueues\"[\n" +
	"\x1dQueuesGarbageCollectionRecord\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\"\xca\x01\n" +
	"!RunQueuesGarbageCollectionRequest\x12/\n" +
	"\x14gc_records_page_size\x18\x01 \x01(\x05R\x11gcRecordsPageSize\x12@\n" +
	"\x1dgc_record_schedules_page_size\x18\x02 \x01(\x05R\x19gcRecordSchedulesPageSize\x122\n" +
	"\x15max_visited_schedules\x18\x03 \x01(\x05R\x13maxVisitedSchedules\"$\n" +
	"\"RunQueuesGarbageCollectionResponse*x\n" +
	"\fIntervalUnit\x12\x19\n" +
	"\x15INTERVAL_UNIT_INVALID\x10\x00\x12\x19\n" +
	"\x15INTERVAL_UNIT_SECONDS\x10\x01\x12\x19\n" +
	"\x15INTERVAL_UNIT_MINUTES\x10\x02\x12\x17\n" +
	"\x13INTERVAL_UNIT_HOURS\x10\x03B#Z!github.com/evrblk/moab/pkg/corepbb\x06proto3"

var (
	file_pkg_corepb_queues_proto_rawDescOnce sync.Once
	file_pkg_corepb_queues_proto_rawDescData []byte
)

func file_pkg_corepb_queues_proto_rawDescGZIP() []byte {
	file_pkg_corepb_queues_proto_rawDescOnce.Do(func() {
		file_pkg_corepb_queues_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_corepb_queues_proto_rawDesc), len(file_pkg_corepb_queues_proto_rawDesc)))
	})
	return file_pkg_corepb_queues_proto_rawDescData
}

var file_pkg_corepb_queues_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_corepb_queues_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_pkg_corepb_queues_proto_goTypes = []any{
	(IntervalUnit)(0),                          // 0: com.evrblk.moab.corepb.IntervalUnit
	(*Queue)(nil),                              // 1: com.evrblk.moab.corepb.Queue
	(*QueueId)(nil),                            // 2: com.evrblk.moab.corepb.QueueId
	(*DeadLetterQueueConfig)(nil),              // 3: com.evrblk.moab.corepb.DeadLetterQueueConfig
	(*DequeuingSettings)(nil),                  // 4: com.evrblk.moab.corepb.DequeuingSettings
	(*TokenBucketRateLimiting)(nil),            // 5: com.evrblk.moab.corepb.TokenBucketRateLimiting
	(*Schedule)(nil),                           // 6: com.evrblk.moab.corepb.Schedule
	(*ScheduleId)(nil),                         // 7: com.evrblk.moab.corepb.ScheduleId
	(*CreateQueueRequest)(nil),                 // 8: com.evrblk.moab.corepb.CreateQueueRequest
	(*CreateQueueResponse)(nil),                // 9: com.evrblk.moab.corepb.CreateQueueResponse
	(*GetQueueRequest)(nil),                    // 10: com.evrblk.moab.corepb.GetQueueRequest
	(*GetQueueResponse)(nil),                   // 11: com.evrblk.moab.corepb.GetQueueResponse
	(*GetQueueByNameRequest)(nil),              // 12: com.evrblk.moab.corepb.GetQueueByNameRequest
	(*GetQueueByNameResponse)(nil),             // 13: com.evrblk.moab.corepb.GetQueueByNameResponse
	(*UpdateQueueRequest)(nil),                 // 14: com.evrblk.moab.corepb.UpdateQueueRequest
	(*UpdateQueueResponse)(nil),                // 15: com.evrblk.moab.corepb.UpdateQueueResponse
	(*DeleteQueueRequest)(nil),                 // 16: com.evrblk.moab.corepb.DeleteQueueRequest
	(*DeleteQueueResponse)(nil),                // 17: com.evrblk.moab.corepb.DeleteQueueResponse
	(*ListQueuesRequest)(nil),                  // 18: com.evrblk.moab.corepb.ListQueuesRequest
	(*ListQueuesResponse)(nil),                 // 19: com.evrblk.moab.corepb.ListQueuesResponse
	(*CreateScheduleRequest)(nil),              // 20: com.evrblk.moab.corepb.CreateScheduleRequest
	(*CreateScheduleResponse)(nil),             // 21: com.evrblk.moab.corepb.CreateScheduleResponse
	(*GetScheduleRequest)(nil),                 // 22: com.evrblk.moab.corepb.GetScheduleRequest
	(*GetScheduleResponse)(nil),                // 23: com.evrblk.moab.corepb.GetScheduleResponse
	(*ListSchedulesRequest)(nil),               // 24: com.evrblk.moab.corepb.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),              // 25: com.evrblk.moab.corepb.ListSchedulesResponse
	(*UpdateScheduleRequest)(nil),              // 26: com.evrblk.moab.corepb.UpdateScheduleRequest
	(*UpdateScheduleResponse)(nil),             // 27: com.evrblk.moab.corepb.UpdateScheduleResponse
	(*DeleteScheduleRequest)(nil),              // 28: com.evrblk.moab.corepb.DeleteScheduleRequest
	(*DeleteScheduleResponse)(nil),             // 29: com.evrblk.moab.corepb.DeleteScheduleResponse
	(*DequeSchedulesRequest)(nil),              // 30: com.evrblk.moab.corepb.DequeSchedulesRequest
	(*DequeSchedulesResponse)(nil),             // 31: com.evrblk.moab.corepb.DequeSchedulesResponse
	(*DequeSchedulesResponseEntry)(nil),        // 32: com.evrblk.moab.corepb.DequeSchedulesResponseEntry
	(*ReportSchedulesStatusRequest)(nil),       // 33: com.evrblk.moab.corepb.ReportSchedulesStatusRequest
	(*ReportSchedulesStatusResponse)(nil),      // 34: com.evrblk.moab.corepb.ReportSchedulesStatusResponse
	(*QueuesCounter)(nil),                      // 35: com.evrblk.moab.corepb.QueuesCounter
	(*QueuesGarbageCollectionRecord)(nil),      // 36: com.evrblk.moab.corepb.QueuesGarbageCollectionRecord
	(*RunQueuesGarbageCollectionRequest)(nil),  // 37: com.evrblk.moab.corepb.RunQueuesGarbageCollectionRequest
	(*RunQueuesGarbageCollectionResponse)(nil), // 38: com.evrblk.moab.corepb.RunQueuesGarbageCollectionResponse
	(*RetryStrategy)(nil),                      // 39: com.evrblk.moab.corepb.RetryStrategy
	(*PaginationToken)(nil),                    // 40: com.evrblk.moab.corepb.PaginationToken
}
var file_pkg_corepb_queues_proto_depIdxs = []int32{
	2,  // 0: com.evrblk.moab.corepb.Queue.id:type_name -> com.evrblk.moab.corepb.QueueId
	39, // 1: com.evrblk.moab.corepb.Queue.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	4,  // 2: com.evrblk.moab.corepb.Queue.dequeuing_settings:type_name -> com.evrblk.moab.corepb.DequeuingSettings
	3,  // 3: com.evrblk.moab.corepb.Queue.dead_letter_queue_config:type_name -> com.evrblk.moab.corepb.DeadLetterQueueConfig
	5,  // 4: com.evrblk.moab.corepb.DequeuingSettings.rate_limiting:type_name -> com.evrblk.moab.corepb.TokenBucketRateLimiting
	0,  // 5: com.evrblk.moab.corepb.TokenBucketRateLimiting.interval_unit:type_name -> com.evrblk.moab.corepb.IntervalUnit
	7,  // 6: com.evrblk.moab.corepb.Schedule.id:type_name -> com.evrblk.moab.corepb.ScheduleId
	39, // 7: com.evrblk.moab.corepb.Schedule.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	2,  // 8: com.evrblk.moab.corepb.CreateQueueRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	39, // 9: com.evrblk.moab.corepb.CreateQueueRequest.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	4,  // 10: com.evrblk.moab.corepb.CreateQueueRequest.dequeuing_settings:type_name -> com.evrblk.moab.corepb.DequeuingSettings
	3,  // 11: com.evrblk.moab.corepb.CreateQueueRequest.dead_letter_queue_config:type_name -> com.evrblk.moab.corepb.DeadLetterQueueConfig
	1,  // 12: com.evrblk.moab.corepb.CreateQueueResponse.queue:type_name -> com.evrblk.moab.corepb.Queue
	2,  // 13: com.evrblk.moab.corepb.GetQueueRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	1,  // 14: com.evrblk.moab.corepb.GetQueueResponse.queue:type_name -> com.evrblk.moab.corepb.Queue
	1,  // 15: com.evrblk.moab.corepb.GetQueueByNameResponse.queue:type_name -> com.evrblk.moab.corepb.Queue
	39, // 16: com.evrblk.moab.corepb.UpdateQueueRequest.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	4,  // 17: com.evrblk.moab.corepb.UpdateQueueRequest.dequeuing_settings:type_name -> com.evrblk.moab.corepb.DequeuingSettings
	3,  // 18: com.evrblk.moab.corepb.UpdateQueueRequest.dead_letter_queue_config:type_name -> com.evrblk.moab.corepb.DeadLetterQueueConfig
	1,  // 19: com.evrblk.moab.corepb.UpdateQueueResponse.queue:type_name -> com.evrblk.moab.corepb.Queue
	40, // 20: com.evrblk.moab.corepb.ListQueuesRequest.pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	1,  // 21: com.evrblk.moab.corepb.ListQueuesResponse.queues:type_name -> com.evrblk.moab.corepb.Queue
	40, // 22: com.evrblk.moab.corepb.ListQueuesResponse.next_pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	40, // 23: com.evrblk.moab.corepb.ListQueuesResponse.previous_pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	39, // 24: com.evrblk.moab.corepb.CreateScheduleRequest.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	6,  // 25: com.evrblk.moab.corepb.CreateScheduleResponse.schedule:type_name -> com.evrblk.moab.corepb.Schedule
	6,  // 26: com.evrblk.moab.corepb.GetScheduleResponse.schedule:type_name -> com.evrblk.moab.corepb.Schedule
	2,  // 27: com.evrblk.moab.corepb.ListSchedulesRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	40, // 28: com.evrblk.moab.corepb.ListSchedulesRequest.pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	6,  // 29: com.evrblk.moab.corepb.ListSchedulesResponse.schedules:type_name -> com.evrblk.moab.corepb.Schedule
	40, // 30: com.evrblk.moab.corepb.ListSchedulesResponse.next_pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	40, // 31: com.evrblk.moab.corepb.ListSchedulesResponse.previous_pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	39, // 32: com.evrblk.moab.corepb.UpdateScheduleRequest.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	6,  // 33: com.evrblk.moab.corepb.UpdateScheduleResponse.schedule:type_name -> com.evrblk.moab.corepb.Schedule
	32, // 34: com.evrblk.moab.corepb.DequeSchedulesResponse.entries:type_name -> com.evrblk.moab.corepb.DequeSchedulesResponseEntry
	6,  // 35: com.evrblk.moab.corepb.DequeSchedulesResponseEntry.schedule:type_name -> com.evrblk.moab.corepb.Schedule
	1,  // 36: com.evrblk.moab.corepb.DequeSchedulesResponseEntry.queue:type_name -> com.evrblk.moab.corepb.Queue
	7,  // 37: com.evrblk.moab.corepb.ReportSchedulesStatusRequest.schedule_id:type_name -> com.evrblk.moab.corepb.ScheduleId
	2,  // 38: com.evrblk.moab.corepb.QueuesGarbageCollectionRecord.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_pkg_corepb_queues_proto_init() }
func file_pkg_corepb_queues_proto_init() {
	if File_pkg_corepb_queues_proto != nil {
		return
	}
	file_pkg_corepb_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_corepb_queues_proto_rawDesc), len(file_pkg_corepb_queues_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_corepb_queues_proto_goTypes,
		DependencyIndexes: file_pkg_corepb_queues_proto_depIdxs,
		EnumInfos:         file_pkg_corepb_queues_proto_enumTypes,
		MessageInfos:      file_pkg_corepb_queues_proto_msgTypes,
	}.Build()
	File_pkg_corepb_queues_proto = out.File
	file_pkg_corepb_queues_proto_goTypes = nil
	file_pkg_corepb_queues_proto_depIdxs = nil
}
