// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: pkg/corepb/tasks.proto

package corepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_INVALID     TaskState = 0
	TaskState_TASK_STATE_ENQUEUED    TaskState = 1
	TaskState_TASK_STATE_IN_PROGRESS TaskState = 2
	TaskState_TASK_STATE_DEAD        TaskState = 3
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_INVALID",
		1: "TASK_STATE_ENQUEUED",
		2: "TASK_STATE_IN_PROGRESS",
		3: "TASK_STATE_DEAD",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_INVALID":     0,
		"TASK_STATE_ENQUEUED":    1,
		"TASK_STATE_IN_PROGRESS": 2,
		"TASK_STATE_DEAD":        3,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_tasks_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_pkg_corepb_tasks_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{0}
}

type EnqueueRequestEntry_OverwriteOnDuplicate int32

const (
	EnqueueRequestEntry_OVERWRITE_ON_DUPLICATE_INVALID      EnqueueRequestEntry_OverwriteOnDuplicate = 0
	EnqueueRequestEntry_OVERWRITE_ON_DUPLICATE_PAYLOAD      EnqueueRequestEntry_OverwriteOnDuplicate = 1
	EnqueueRequestEntry_OVERWRITE_ON_DUPLICATE_SCHEDULED_AT EnqueueRequestEntry_OverwriteOnDuplicate = 2
	EnqueueRequestEntry_OVERWRITE_ON_DUPLICATE_EXPIRES_AT   EnqueueRequestEntry_OverwriteOnDuplicate = 3
)

// Enum value maps for EnqueueRequestEntry_OverwriteOnDuplicate.
var (
	EnqueueRequestEntry_OverwriteOnDuplicate_name = map[int32]string{
		0: "OVERWRITE_ON_DUPLICATE_INVALID",
		1: "OVERWRITE_ON_DUPLICATE_PAYLOAD",
		2: "OVERWRITE_ON_DUPLICATE_SCHEDULED_AT",
		3: "OVERWRITE_ON_DUPLICATE_EXPIRES_AT",
	}
	EnqueueRequestEntry_OverwriteOnDuplicate_value = map[string]int32{
		"OVERWRITE_ON_DUPLICATE_INVALID":      0,
		"OVERWRITE_ON_DUPLICATE_PAYLOAD":      1,
		"OVERWRITE_ON_DUPLICATE_SCHEDULED_AT": 2,
		"OVERWRITE_ON_DUPLICATE_EXPIRES_AT":   3,
	}
)

func (x EnqueueRequestEntry_OverwriteOnDuplicate) Enum() *EnqueueRequestEntry_OverwriteOnDuplicate {
	p := new(EnqueueRequestEntry_OverwriteOnDuplicate)
	*p = x
	return p
}

func (x EnqueueRequestEntry_OverwriteOnDuplicate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnqueueRequestEntry_OverwriteOnDuplicate) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_tasks_proto_enumTypes[1].Descriptor()
}

func (EnqueueRequestEntry_OverwriteOnDuplicate) Type() protoreflect.EnumType {
	return &file_pkg_corepb_tasks_proto_enumTypes[1]
}

func (x EnqueueRequestEntry_OverwriteOnDuplicate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnqueueRequestEntry_OverwriteOnDuplicate.Descriptor instead.
func (EnqueueRequestEntry_OverwriteOnDuplicate) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{5, 0}
}

type ReportStatusRequestEntry_Status int32

const (
	ReportStatusRequestEntry_STATUS_INVALID     ReportStatusRequestEntry_Status = 0
	ReportStatusRequestEntry_STATUS_SUCCEEDED   ReportStatusRequestEntry_Status = 1
	ReportStatusRequestEntry_STATUS_IN_PROGRESS ReportStatusRequestEntry_Status = 2
	ReportStatusRequestEntry_STATUS_FAILED      ReportStatusRequestEntry_Status = 3
)

// Enum value maps for ReportStatusRequestEntry_Status.
var (
	ReportStatusRequestEntry_Status_name = map[int32]string{
		0: "STATUS_INVALID",
		1: "STATUS_SUCCEEDED",
		2: "STATUS_IN_PROGRESS",
		3: "STATUS_FAILED",
	}
	ReportStatusRequestEntry_Status_value = map[string]int32{
		"STATUS_INVALID":     0,
		"STATUS_SUCCEEDED":   1,
		"STATUS_IN_PROGRESS": 2,
		"STATUS_FAILED":      3,
	}
)

func (x ReportStatusRequestEntry_Status) Enum() *ReportStatusRequestEntry_Status {
	p := new(ReportStatusRequestEntry_Status)
	*p = x
	return p
}

func (x ReportStatusRequestEntry_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatusRequestEntry_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_tasks_proto_enumTypes[2].Descriptor()
}

func (ReportStatusRequestEntry_Status) Type() protoreflect.EnumType {
	return &file_pkg_corepb_tasks_proto_enumTypes[2]
}

func (x ReportStatusRequestEntry_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatusRequestEntry_Status.Descriptor instead.
func (ReportStatusRequestEntry_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{10, 0}
}

type RestartTasksResponseEntry_Result int32

const (
	RestartTasksResponseEntry_RESULT_INVALID         RestartTasksResponseEntry_Result = 0
	RestartTasksResponseEntry_RESULT_RESTARTED       RestartTasksResponseEntry_Result = 1
	RestartTasksResponseEntry_RESULT_NOT_FOUND       RestartTasksResponseEntry_Result = 2
	RestartTasksResponseEntry_RESULT_NOT_DEAD        RestartTasksResponseEntry_Result = 3
	RestartTasksResponseEntry_RESULT_DEDUPE_CONFLICT RestartTasksResponseEntry_Result = 4
)

// Enum value maps for RestartTasksResponseEntry_Result.
var (
	RestartTasksResponseEntry_Result_name = map[int32]string{
		0: "RESULT_INVALID",
		1: "RESULT_RESTARTED",
		2: "RESULT_NOT_FOUND",
		3: "RESULT_NOT_DEAD",
		4: "RESULT_DEDUPE_CONFLICT",
	}
	RestartTasksResponseEntry_Result_value = map[string]int32{
		"RESULT_INVALID":         0,
		"RESULT_RESTARTED":       1,
		"RESULT_NOT_FOUND":       2,
		"RESULT_NOT_DEAD":        3,
		"RESULT_DEDUPE_CONFLICT": 4,
	}
)

func (x RestartTasksResponseEntry_Result) Enum() *RestartTasksResponseEntry_Result {
	p := new(RestartTasksResponseEntry_Result)
	*p = x
	return p
}

func (x RestartTasksResponseEntry_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartTasksResponseEntry_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_corepb_tasks_proto_enumTypes[3].Descriptor()
}

func (RestartTasksResponseEntry_Result) Type() protoreflect.EnumType {
	return &file_pkg_corepb_tasks_proto_enumTypes[3]
}

func (x RestartTasksResponseEntry_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartTasksResponseEntry_Result.Descriptor instead.
func (RestartTasksResponseEntry_Result) EnumDescriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{17, 0}
}

type Task struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        *TaskId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload                   []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt                 int64                  `protobuf:"fixed64,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt               int64                  `protobuf:"fixed64,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	ExpiresAt                 int64                  `protobuf:"fixed64,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	DedupeKey                 string                 `protobuf:"bytes,6,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`
	State                     TaskState              `protobuf:"varint,7,opt,name=state,proto3,enum=com.evrblk.moab.corepb.TaskState" json:"state,omitempty"`
	Attempts                  int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	VisibleAt                 int64                  `protobuf:"fixed64,9,opt,name=visible_at,json=visibleAt,proto3" json:"visible_at,omitempty"`
	LastFailedAt              int64                  `protobuf:"fixed64,10,opt,name=last_failed_at,json=lastFailedAt,proto3" json:"last_failed_at,omitempty"`
	DebugInfo                 []byte                 `protobuf:"bytes,11,opt,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty"`
	KeepaliveTimeoutInSeconds int64                  `protobuf:"varint,12,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy         `protobuf:"bytes,13,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	ThreadId                  string                 `protobuf:"bytes,14,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() *TaskId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *Task) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Task) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_INVALID
}

func (x *Task) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Task) GetVisibleAt() int64 {
	if x != nil {
		return x.VisibleAt
	}
	return 0
}

func (x *Task) GetLastFailedAt() int64 {
	if x != nil {
		return x.LastFailedAt
	}
	return 0
}

func (x *Task) GetDebugInfo() []byte {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

func (x *Task) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *Task) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *Task) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type TaskId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"fixed64,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	QueueId       uint64                 `protobuf:"fixed64,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	TaskId        uint64                 `protobuf:"fixed64,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskId) Reset() {
	*x = TaskId{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskId) ProtoMessage() {}

func (x *TaskId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskId.ProtoReflect.Descriptor instead.
func (*TaskId) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *TaskId) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TaskId) GetQueueId() uint64 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *TaskId) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ExpirationIndexRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *TaskId                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"fixed64,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpirationIndexRecord) Reset() {
	*x = ExpirationIndexRecord{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpirationIndexRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationIndexRecord) ProtoMessage() {}

func (x *ExpirationIndexRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationIndexRecord.ProtoReflect.Descriptor instead.
func (*ExpirationIndexRecord) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *ExpirationIndexRecord) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *ExpirationIndexRecord) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Thread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	HeadTaskId    *TaskId                `protobuf:"bytes,2,opt,name=head_task_id,json=headTaskId,proto3" json:"head_task_id,omitempty"`
	ScheduledAt   int64                  `protobuf:"fixed64,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	VisibleAt     int64                  `protobuf:"fixed64,4,opt,name=visible_at,json=visibleAt,proto3" json:"visible_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *Thread) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Thread) GetHeadTaskId() *TaskId {
	if x != nil {
		return x.HeadTaskId
	}
	return nil
}

func (x *Thread) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *Thread) GetVisibleAt() int64 {
	if x != nil {
		return x.VisibleAt
	}
	return 0
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Entries       []*EnqueueRequestEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueueRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *EnqueueRequest) GetEntries() []*EnqueueRequestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type EnqueueRequestEntry struct {
	state                     protoimpl.MessageState                     `protogen:"open.v1"`
	Payload                   []byte                                     `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ScheduledAt               int64                                      `protobuf:"fixed64,2,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	ExpiresAt                 int64                                      `protobuf:"fixed64,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	DedupeKey                 string                                     `protobuf:"bytes,4,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`
	KeepaliveTimeoutInSeconds int64                                      `protobuf:"varint,5,opt,name=keepalive_timeout_in_seconds,json=keepaliveTimeoutInSeconds,proto3" json:"keepalive_timeout_in_seconds,omitempty"`
	RetryStrategy             *RetryStrategy                             `protobuf:"bytes,6,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	OverwriteOnDuplicate      []EnqueueRequestEntry_OverwriteOnDuplicate `protobuf:"varint,7,rep,packed,name=overwrite_on_duplicate,json=overwriteOnDuplicate,proto3,enum=com.evrblk.moab.corepb.EnqueueRequestEntry_OverwriteOnDuplicate" json:"overwrite_on_duplicate,omitempty"`
	ThreadId                  string                                     `protobuf:"bytes,8,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *EnqueueRequestEntry) Reset() {
	*x = EnqueueRequestEntry{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequestEntry) ProtoMessage() {}

func (x *EnqueueRequestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequestEntry.ProtoReflect.Descriptor instead.
func (*EnqueueRequestEntry) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *EnqueueRequestEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequestEntry) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *EnqueueRequestEntry) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *EnqueueRequestEntry) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *EnqueueRequestEntry) GetKeepaliveTimeoutInSeconds() int64 {
	if x != nil {
		return x.KeepaliveTimeoutInSeconds
	}
	return 0
}

func (x *EnqueueRequestEntry) GetRetryStrategy() *RetryStrategy {
	if x != nil {
		return x.RetryStrategy
	}
	return nil
}

func (x *EnqueueRequestEntry) GetOverwriteOnDuplicate() []EnqueueRequestEntry_OverwriteOnDuplicate {
	if x != nil {
		return x.OverwriteOnDuplicate
	}
	return nil
}

func (x *EnqueueRequestEntry) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *EnqueueResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DequeueRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueueId           *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	DequeuingSettings *DequeuingSettings     `protobuf:"bytes,2,opt,name=dequeuing_settings,json=dequeuingSettings,proto3" json:"dequeuing_settings,omitempty"`
	DequeueLimit      int32                  `protobuf:"varint,3,opt,name=dequeue_limit,json=dequeueLimit,proto3" json:"dequeue_limit,omitempty"`
	// Resolved from Queue by the server, same as dequeuing_settings — the
	// tasks core never reads queue config itself. Used to decide, when a
	// keepalive timeout is discovered here, whether the task should be
	// dead-lettered or deleted outright once its retries are exhausted.
	DeadLetterQueueConfig *DeadLetterQueueConfig `protobuf:"bytes,4,opt,name=dead_letter_queue_config,json=deadLetterQueueConfig,proto3" json:"dead_letter_queue_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *DequeueRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *DequeueRequest) GetDequeuingSettings() *DequeuingSettings {
	if x != nil {
		return x.DequeuingSettings
	}
	return nil
}

func (x *DequeueRequest) GetDequeueLimit() int32 {
	if x != nil {
		return x.DequeueLimit
	}
	return 0
}

func (x *DequeueRequest) GetDeadLetterQueueConfig() *DeadLetterQueueConfig {
	if x != nil {
		return x.DeadLetterQueueConfig
	}
	return nil
}

type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *DequeueResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ReportStatusRequest struct {
	state   protoimpl.MessageState      `protogen:"open.v1"`
	QueueId *QueueId                    `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Entries []*ReportStatusRequestEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// Resolved from Queue by the server, same as DequeueRequest's — used to
	// route an explicit STATUS_FAILED report to dead/deleted correctly.
	DeadLetterQueueConfig *DeadLetterQueueConfig `protobuf:"bytes,3,opt,name=dead_letter_queue_config,json=deadLetterQueueConfig,proto3" json:"dead_letter_queue_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *ReportStatusRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *ReportStatusRequest) GetEntries() []*ReportStatusRequestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReportStatusRequest) GetDeadLetterQueueConfig() *DeadLetterQueueConfig {
	if x != nil {
		return x.DeadLetterQueueConfig
	}
	return nil
}

type ReportStatusRequestEntry struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	TaskId        *TaskId                         `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Attempt       int32                           `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Status        ReportStatusRequestEntry_Status `protobuf:"varint,3,opt,name=status,proto3,enum=com.evrblk.moab.corepb.ReportStatusRequestEntry_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequestEntry) Reset() {
	*x = ReportStatusRequestEntry{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequestEntry) ProtoMessage() {}

func (x *ReportStatusRequestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequestEntry.ProtoReflect.Descriptor instead.
func (*ReportStatusRequestEntry) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *ReportStatusRequestEntry) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *ReportStatusRequestEntry) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReportStatusRequestEntry) GetStatus() ReportStatusRequestEntry_Status {
	if x != nil {
		return x.Status
	}
	return ReportStatusRequestEntry_STATUS_INVALID
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{11}
}

type DeleteTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	TaskIds       []uint64               `protobuf:"fixed64,2,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTasksRequest) Reset() {
	*x = DeleteTasksRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTasksRequest) ProtoMessage() {}

func (x *DeleteTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTasksRequest.ProtoReflect.Descriptor instead.
func (*DeleteTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTasksRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *DeleteTasksRequest) GetTaskIds() []uint64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type DeleteTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTasksResponse) Reset() {
	*x = DeleteTasksResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTasksResponse) ProtoMessage() {}

func (x *DeleteTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTasksResponse.ProtoReflect.Descriptor instead.
func (*DeleteTasksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{13}
}

type RestartTasksRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	QueueId       *QueueId                    `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Entries       []*RestartTasksRequestEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTasksRequest) Reset() {
	*x = RestartTasksRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTasksRequest) ProtoMessage() {}

func (x *RestartTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTasksRequest.ProtoReflect.Descriptor instead.
func (*RestartTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{14}
}

func (x *RestartTasksRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *RestartTasksRequest) GetEntries() []*RestartTasksRequestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RestartTasksRequestEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId uint64                 `protobuf:"fixed64,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 0 - now (mirrors EnqueueRequestEntry's ScheduledAt).
	ScheduledAt int64 `protobuf:"fixed64,2,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	// 0 - queue default (mirrors EnqueueRequestEntry's ExpiresAt); the tasks
	// core has no way to compute now + Queue.ExpiresInSeconds itself, so the
	// server resolves this the same way it does for Enqueue.
	ExpiresAt     int64 `protobuf:"fixed64,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTasksRequestEntry) Reset() {
	*x = RestartTasksRequestEntry{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTasksRequestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTasksRequestEntry) ProtoMessage() {}

func (x *RestartTasksRequestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTasksRequestEntry.ProtoReflect.Descriptor instead.
func (*RestartTasksRequestEntry) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{15}
}

func (x *RestartTasksRequestEntry) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RestartTasksRequestEntry) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *RestartTasksRequestEntry) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RestartTasksResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Entries       []*RestartTasksResponseEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTasksResponse) Reset() {
	*x = RestartTasksResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTasksResponse) ProtoMessage() {}

func (x *RestartTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTasksResponse.ProtoReflect.Descriptor instead.
func (*RestartTasksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{16}
}

func (x *RestartTasksResponse) GetEntries() []*RestartTasksResponseEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RestartTasksResponseEntry struct {
	state  protoimpl.MessageState           `protogen:"open.v1"`
	TaskId uint64                           `protobuf:"fixed64,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result RestartTasksResponseEntry_Result `protobuf:"varint,2,opt,name=result,proto3,enum=com.evrblk.moab.corepb.RestartTasksResponseEntry_Result" json:"result,omitempty"`
	// Set iff result == RESULT_RESTARTED.
	Task          *Task `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTasksResponseEntry) Reset() {
	*x = RestartTasksResponseEntry{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTasksResponseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTasksResponseEntry) ProtoMessage() {}

func (x *RestartTasksResponseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTasksResponseEntry.ProtoReflect.Descriptor instead.
func (*RestartTasksResponseEntry) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{17}
}

func (x *RestartTasksResponseEntry) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RestartTasksResponseEntry) GetResult() RestartTasksResponseEntry_Result {
	if x != nil {
		return x.Result
	}
	return RestartTasksResponseEntry_RESULT_INVALID
}

func (x *RestartTasksResponseEntry) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{18}
}

func (x *GetStatisticsRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

type GetStatisticsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnqueuedTasksCount   int64                  `protobuf:"varint,1,opt,name=enqueued_tasks_count,json=enqueuedTasksCount,proto3" json:"enqueued_tasks_count,omitempty"`
	InProgressTasksCount int64                  `protobuf:"varint,2,opt,name=in_progress_tasks_count,json=inProgressTasksCount,proto3" json:"in_progress_tasks_count,omitempty"`
	DeadTasksCount       int64                  `protobuf:"varint,3,opt,name=dead_tasks_count,json=deadTasksCount,proto3" json:"dead_tasks_count,omitempty"`
	ProcessedTasksCount  int64                  `protobuf:"varint,4,opt,name=processed_tasks_count,json=processedTasksCount,proto3" json:"processed_tasks_count,omitempty"`
	ExpiredTasksCount    int64                  `protobuf:"varint,5,opt,name=expired_tasks_count,json=expiredTasksCount,proto3" json:"expired_tasks_count,omitempty"`
	// Age of the oldest task actually available to dequeue right now, not
	// every ENQUEUED task: a non-head member of a thread whose head is busy
	// (IN_PROGRESS) is excluded, since it cannot be dequeued until the head
	// finishes.
	AgeOfOldestEnqueuedTask int64 `protobuf:"varint,6,opt,name=age_of_oldest_enqueued_task,json=ageOfOldestEnqueuedTask,proto3" json:"age_of_oldest_enqueued_task,omitempty"`
	TaskIdSequence          int64 `protobuf:"varint,7,opt,name=task_id_sequence,json=taskIdSequence,proto3" json:"task_id_sequence,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{19}
}

func (x *GetStatisticsResponse) GetEnqueuedTasksCount() int64 {
	if x != nil {
		return x.EnqueuedTasksCount
	}
	return 0
}

func (x *GetStatisticsResponse) GetInProgressTasksCount() int64 {
	if x != nil {
		return x.InProgressTasksCount
	}
	return 0
}

func (x *GetStatisticsResponse) GetDeadTasksCount() int64 {
	if x != nil {
		return x.DeadTasksCount
	}
	return 0
}

func (x *GetStatisticsResponse) GetProcessedTasksCount() int64 {
	if x != nil {
		return x.ProcessedTasksCount
	}
	return 0
}

func (x *GetStatisticsResponse) GetExpiredTasksCount() int64 {
	if x != nil {
		return x.ExpiredTasksCount
	}
	return 0
}

func (x *GetStatisticsResponse) GetAgeOfOldestEnqueuedTask() int64 {
	if x != nil {
		return x.AgeOfOldestEnqueuedTask
	}
	return 0
}

func (x *GetStatisticsResponse) GetTaskIdSequence() int64 {
	if x != nil {
		return x.TaskIdSequence
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *TaskId                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{20}
}

func (x *GetTaskRequest) GetTaskId() *TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{21}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type PurgeQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeQueueRequest) Reset() {
	*x = PurgeQueueRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeQueueRequest) ProtoMessage() {}

func (x *PurgeQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeQueueRequest.ProtoReflect.Descriptor instead.
func (*PurgeQueueRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{22}
}

func (x *PurgeQueueRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

type PurgeQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeQueueResponse) Reset() {
	*x = PurgeQueueResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeQueueResponse) ProtoMessage() {}

func (x *PurgeQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeQueueResponse.ProtoReflect.Descriptor instead.
func (*PurgeQueueResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{23}
}

type ListTasksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QueueId         *QueueId               `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	PaginationToken *PaginationToken       `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken,proto3" json:"pagination_token,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{24}
}

func (x *ListTasksRequest) GetQueueId() *QueueId {
	if x != nil {
		return x.QueueId
	}
	return nil
}

func (x *ListTasksRequest) GetPaginationToken() *PaginationToken {
	if x != nil {
		return x.PaginationToken
	}
	return nil
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTasksResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Tasks                   []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPaginationToken     *PaginationToken       `protobuf:"bytes,2,opt,name=next_pagination_token,json=nextPaginationToken,proto3" json:"next_pagination_token,omitempty"`
	PreviousPaginationToken *PaginationToken       `protobuf:"bytes,3,opt,name=previous_pagination_token,json=previousPaginationToken,proto3" json:"previous_pagination_token,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{25}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetNextPaginationToken() *PaginationToken {
	if x != nil {
		return x.NextPaginationToken
	}
	return nil
}

func (x *ListTasksResponse) GetPreviousPaginationToken() *PaginationToken {
	if x != nil {
		return x.PreviousPaginationToken
	}
	return nil
}

type RunTasksGarbageCollectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxVisitedTasks int32                  `protobuf:"varint,1,opt,name=max_visited_tasks,json=maxVisitedTasks,proto3" json:"max_visited_tasks,omitempty"`
	PageSize        int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunTasksGarbageCollectionRequest) Reset() {
	*x = RunTasksGarbageCollectionRequest{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTasksGarbageCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTasksGarbageCollectionRequest) ProtoMessage() {}

func (x *RunTasksGarbageCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTasksGarbageCollectionRequest.ProtoReflect.Descriptor instead.
func (*RunTasksGarbageCollectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{26}
}

func (x *RunTasksGarbageCollectionRequest) GetMaxVisitedTasks() int32 {
	if x != nil {
		return x.MaxVisitedTasks
	}
	return 0
}

func (x *RunTasksGarbageCollectionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RunTasksGarbageCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTasksGarbageCollectionResponse) Reset() {
	*x = RunTasksGarbageCollectionResponse{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTasksGarbageCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTasksGarbageCollectionResponse) ProtoMessage() {}

func (x *RunTasksGarbageCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTasksGarbageCollectionResponse.ProtoReflect.Descriptor instead.
func (*RunTasksGarbageCollectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{27}
}

type TasksCounter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnqueuedTasksCount   int64                  `protobuf:"varint,1,opt,name=enqueued_tasks_count,json=enqueuedTasksCount,proto3" json:"enqueued_tasks_count,omitempty"`
	InProgressTasksCount int64                  `protobuf:"varint,2,opt,name=in_progress_tasks_count,json=inProgressTasksCount,proto3" json:"in_progress_tasks_count,omitempty"`
	DeadTasksCount       int64                  `protobuf:"varint,3,opt,name=dead_tasks_count,json=deadTasksCount,proto3" json:"dead_tasks_count,omitempty"`
	// Monotonic lifetime counters, distinct from the current-occupancy gauges
	// above (never decremented): total tasks ever completed successfully, and
	// total tasks ever deleted for having expired (whether while ENQUEUED,
	// IN_PROGRESS-then-failed, or DEAD past DLQ retention).
	ProcessedTasksCount int64 `protobuf:"varint,4,opt,name=processed_tasks_count,json=processedTasksCount,proto3" json:"processed_tasks_count,omitempty"`
	ExpiredTasksCount   int64 `protobuf:"varint,5,opt,name=expired_tasks_count,json=expiredTasksCount,proto3" json:"expired_tasks_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TasksCounter) Reset() {
	*x = TasksCounter{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksCounter) ProtoMessage() {}

func (x *TasksCounter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksCounter.ProtoReflect.Descriptor instead.
func (*TasksCounter) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{28}
}

func (x *TasksCounter) GetEnqueuedTasksCount() int64 {
	if x != nil {
		return x.EnqueuedTasksCount
	}
	return 0
}

func (x *TasksCounter) GetInProgressTasksCount() int64 {
	if x != nil {
		return x.InProgressTasksCount
	}
	return 0
}

func (x *TasksCounter) GetDeadTasksCount() int64 {
	if x != nil {
		return x.DeadTasksCount
	}
	return 0
}

func (x *TasksCounter) GetProcessedTasksCount() int64 {
	if x != nil {
		return x.ProcessedTasksCount
	}
	return 0
}

func (x *TasksCounter) GetExpiredTasksCount() int64 {
	if x != nil {
		return x.ExpiredTasksCount
	}
	return 0
}

type QueueState struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TaskIdSequence        uint64                 `protobuf:"fixed64,1,opt,name=task_id_sequence,json=taskIdSequence,proto3" json:"task_id_sequence,omitempty"`
	LastVisitedEnqueued   int64                  `protobuf:"varint,2,opt,name=last_visited_enqueued,json=lastVisitedEnqueued,proto3" json:"last_visited_enqueued,omitempty"`
	LastVisitedInProgress int64                  `protobuf:"varint,3,opt,name=last_visited_in_progress,json=lastVisitedInProgress,proto3" json:"last_visited_in_progress,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueueState) Reset() {
	*x = QueueState{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueState) ProtoMessage() {}

func (x *QueueState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueState.ProtoReflect.Descriptor instead.
func (*QueueState) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{29}
}

func (x *QueueState) GetTaskIdSequence() uint64 {
	if x != nil {
		return x.TaskIdSequence
	}
	return 0
}

func (x *QueueState) GetLastVisitedEnqueued() int64 {
	if x != nil {
		return x.LastVisitedEnqueued
	}
	return 0
}

func (x *QueueState) GetLastVisitedInProgress() int64 {
	if x != nil {
		return x.LastVisitedInProgress
	}
	return 0
}

type RateLimiterState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tokens         int64                  `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	LastRefilledAt int64                  `protobuf:"fixed64,2,opt,name=last_refilled_at,json=lastRefilledAt,proto3" json:"last_refilled_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RateLimiterState) Reset() {
	*x = RateLimiterState{}
	mi := &file_pkg_corepb_tasks_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimiterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimiterState) ProtoMessage() {}

func (x *RateLimiterState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_corepb_tasks_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimiterState.ProtoReflect.Descriptor instead.
func (*RateLimiterState) Descriptor() ([]byte, []int) {
	return file_pkg_corepb_tasks_proto_rawDescGZIP(), []int{30}
}

func (x *RateLimiterState) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *RateLimiterState) GetLastRefilledAt() int64 {
	if x != nil {
		return x.LastRefilledAt
	}
	return 0
}

var File_pkg_corepb_tasks_proto protoreflect.FileDescriptor

const file_pkg_corepb_tasks_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/corepb/tasks.proto\x12\x16com.evrblk.moab.corepb\x1a\x17pkg/corepb/common.proto\x1a\x17pkg/corepb/queues.proto\"\xb5\x04\n" +
	"\x04Task\x12.\n" +
	"\x02id\x18\x01 \x01(\v2\x1e.com.evrblk.moab.corepb.TaskIdR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x10R\tcreatedAt\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\x10R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x10R\texpiresAt\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\x06 \x01(\tR\tdedupeKey\x127\n" +
	"\x05state\x18\a \x01(\x0e2!.com.evrblk.moab.corepb.TaskStateR\x05state\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"visible_at\x18\t \x01(\x10R\tvisibleAt\x12$\n" +
	"\x0elast_failed_at\x18\n" +
	" \x01(\x10R\flastFailedAt\x12\x1d\n" +
	"\n" +
	"debug_info\x18\v \x01(\fR\tdebugInfo\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\f \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\r \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12\x1b\n" +
	"\tthread_id\x18\x0e \x01(\tR\bthreadId\"[\n" +
	"\x06TaskId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x06R\taccountId\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\x06R\aqueueId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x06R\x06taskId\"o\n" +
	"\x15ExpirationIndexRecord\x127\n" +
	"\atask_id\x18\x01 \x01(\v2\x1e.com.evrblk.moab.corepb.TaskIdR\x06taskId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x10R\texpiresAt\"\xa9\x01\n" +
	"\x06Thread\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12@\n" +
	"\fhead_task_id\x18\x02 \x01(\v2\x1e.com.evrblk.moab.corepb.TaskIdR\n" +
	"headTaskId\x12!\n" +
	"\fscheduled_at\x18\x03 \x01(\x10R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"visible_at\x18\x04 \x01(\x10R\tvisibleAt\"\x93\x01\n" +
	"\x0eEnqueueRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12E\n" +
	"\aentries\x18\x02 \x03(\v2+.com.evrblk.moab.corepb.EnqueueRequestEntryR\aentries\"\xe5\x04\n" +
	"\x13EnqueueRequestEntry\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12!\n" +
	"\fscheduled_at\x18\x02 \x01(\x10R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x10R\texpiresAt\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\x04 \x01(\tR\tdedupeKey\x12?\n" +
	"\x1ckeepalive_timeout_in_seconds\x18\x05 \x01(\x03R\x19keepaliveTimeoutInSeconds\x12L\n" +
	"\x0eretry_strategy\x18\x06 \x01(\v2%.com.evrblk.moab.corepb.RetryStrategyR\rretryStrategy\x12v\n" +
	"\x16overwrite_on_duplicate\x18\a \x03(\x0e2@.com.evrblk.moab.corepb.EnqueueRequestEntry.OverwriteOnDuplicateR\x14overwriteOnDuplicate\x12\x1b\n" +
	"\tthread_id\x18\b \x01(\tR\bthreadId\"\xae\x01\n" +
	"\x14OverwriteOnDuplicate\x12\"\n" +
	"\x1eOVERWRITE_ON_DUPLICATE_INVALID\x10\x00\x12\"\n" +
	"\x1eOVERWRITE_ON_DUPLICATE_PAYLOAD\x10\x01\x12'\n" +
	"#OVERWRITE_ON_DUPLICATE_SCHEDULED_AT\x10\x02\x12%\n" +
	"!OVERWRITE_ON_DUPLICATE_EXPIRES_AT\x10\x03\"E\n" +
	"\x0fEnqueueResponse\x122\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1c.com.evrblk.moab.corepb.TaskR\x05tasks\"\xb3\x02\n" +
	"\x0eDequeueRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12X\n" +
	"\x12dequeuing_settings\x18\x02 \x01(\v2).com.evrblk.moab.corepb.DequeuingSettingsR\x11dequeuingSettings\x12#\n" +
	"\rdequeue_limit\x18\x03 \x01(\x05R\fdequeueLimit\x12f\n" +
	"\x18dead_letter_queue_config\x18\x04 \x01(\v2-.com.evrblk.moab.corepb.DeadLetterQueueConfigR\x15deadLetterQueueConfig\"E\n" +
	"\x0fDequeueResponse\x122\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1c.com.evrblk.moab.corepb.TaskR\x05tasks\"\x85\x02\n" +
	"\x13ReportStatusRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12J\n" +
	"\aentries\x18\x02 \x03(\v20.com.evrblk.moab.corepb.ReportStatusRequestEntryR\aentries\x12f\n" +
	"\x18dead_letter_queue_config\x18\x03 \x01(\v2-.com.evrblk.moab.corepb.DeadLetterQueueConfigR\x15deadLetterQueueConfig\"\x9d\x02\n" +
	"\x18ReportStatusRequestEntry\x127\n" +
	"\atask_id\x18\x01 \x01(\v2\x1e.com.evrblk.moab.corepb.TaskIdR\x06taskId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x05R\aattempt\x12O\n" +
	"\x06status\x18\x03 \x01(\x0e27.com.evrblk.moab.corepb.ReportStatusRequestEntry.StatusR\x06status\"]\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_INVALID\x10\x00\x12\x14\n" +
	"\x10STATUS_SUCCEEDED\x10\x01\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03\"\x16\n" +
	"\x14ReportStatusResponse\"k\n" +
	"\x12DeleteTasksRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\x06R\ataskIds\"\x15\n" +
	"\x13DeleteTasksResponse\"\x9d\x01\n" +
	"\x13RestartTasksRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12J\n" +
	"\aentries\x18\x02 \x03(\v20.com.evrblk.moab.corepb.RestartTasksRequestEntryR\aentries\"u\n" +
	"\x18RestartTasksRequestEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x06R\x06taskId\x12!\n" +
	"\fscheduled_at\x18\x02 \x01(\x10R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x10R\texpiresAt\"c\n" +
	"\x14RestartTasksResponse\x12K\n" +
	"\aentries\x18\x01 \x03(\v21.com.evrblk.moab.corepb.RestartTasksResponseEntryR\aentries\"\xb3\x02\n" +
	"\x19RestartTasksResponseEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x06R\x06taskId\x12P\n" +
	"\x06result\x18\x02 \x01(\x0e28.com.evrblk.moab.corepb.RestartTasksResponseEntry.ResultR\x06result\x120\n" +
	"\x04task\x18\x03 \x01(\v2\x1c.com.evrblk.moab.corepb.TaskR\x04task\"y\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_INVALID\x10\x00\x12\x14\n" +
	"\x10RESULT_RESTARTED\x10\x01\x12\x14\n" +
	"\x10RESULT_NOT_FOUND\x10\x02\x12\x13\n" +
	"\x0fRESULT_NOT_DEAD\x10\x03\x12\x1a\n" +
	"\x16RESULT_DEDUPE_CONFLICT\x10\x04\"R\n" +
	"\x14GetStatisticsRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\"\xf6\x02\n" +
	"\x15GetStatisticsResponse\x120\n" +
	"\x14enqueued_tasks_count\x18\x01 \x01(\x03R\x12enqueuedTasksCount\x125\n" +
	"\x17in_progress_tasks_count\x18\x02 \x01(\x03R\x14inProgressTasksCount\x12(\n" +
	"\x10dead_tasks_count\x18\x03 \x01(\x03R\x0edeadTasksCount\x122\n" +
	"\x15processed_tasks_count\x18\x04 \x01(\x03R\x13processedTasksCount\x12.\n" +
	"\x13expired_tasks_count\x18\x05 \x01(\x03R\x11expiredTasksCount\x12<\n" +
	"\x1bage_of_oldest_enqueued_task\x18\x06 \x01(\x03R\x17ageOfOldestEnqueuedTask\x12(\n" +
	"\x10task_id_sequence\x18\a \x01(\x03R\x0etaskIdSequence\"I\n" +
	"\x0eGetTaskRequest\x127\n" +
	"\atask_id\x18\x01 \x01(\v2\x1e.com.evrblk.moab.corepb.TaskIdR\x06taskId\"C\n" +
	"\x0fGetTaskResponse\x120\n" +
	"\x04task\x18\x01 \x01(\v2\x1c.com.evrblk.moab.corepb.TaskR\x04task\"O\n" +
	"\x11PurgeQueueRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\"\x14\n" +
	"\x12PurgeQueueResponse\"\xb8\x01\n" +
	"\x10ListTasksRequest\x12:\n" +
	"\bqueue_id\x18\x01 \x01(\v2\x1f.com.evrblk.moab.corepb.QueueIdR\aqueueId\x12R\n" +
	"\x10pagination_token\x18\x02 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x0fpaginationToken\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x89\x02\n" +
	"\x11ListTasksResponse\x122\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1c.com.evrblk.moab.corepb.TaskR\x05tasks\x12[\n" +
	"\x15next_pagination_token\x18\x02 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x13nextPaginationToken\x12c\n" +
	"\x19previous_pagination_token\x18\x03 \x01(\v2'.com.evrblk.moab.corepb.PaginationTokenR\x17previousPaginationToken\"k\n" +
	" RunTasksGarbageCollectionRequest\x12*\n" +
	"\x11max_visited_tasks\x18\x01 \x01(\x05R\x0fmaxVisitedTasks\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"#\n" +
	"!RunTasksGarbageCollectionResponse\"\x85\x02\n" +
	"\fTasksCounter\x120\n" +
	"\x14enqueued_tasks_count\x18\x01 \x01(\x03R\x12enqueuedTasksCount\x125\n" +
	"\x17in_progress_tasks_count\x18\x02 \x01(\x03R\x14inProgressTasksCount\x12(\n" +
	"\x10dead_tasks_count\x18\x03 \x01(\x03R\x0edeadTasksCount\x122\n" +
	"\x15processed_tasks_count\x18\x04 \x01(\x03R\x13processedTasksCount\x12.\n" +
	"\x13expired_tasks_count\x18\x05 \x01(\x03R\x11expiredTasksCount\"\xa3\x01\n" +
	"\n" +
	"QueueState\x12(\n" +
	"\x10task_id_sequence\x18\x01 \x01(\x06R\x0etaskIdSequence\x122\n" +
	"\x15last_visited_enqueued\x18\x02 \x01(\x03R\x13lastVisitedEnqueued\x127\n" +
	"\x18last_visited_in_progress\x18\x03 \x01(\x03R\x15lastVisitedInProgress\"T\n" +
	"\x10RateLimiterState\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\x03R\x06tokens\x12(\n" +
	"\x10last_refilled_at\x18\x02 \x01(\x10R\x0elastRefilledAt*m\n" +
	"\tTaskState\x12\x16\n" +
	"\x12TASK_STATE_INVALID\x10\x00\x12\x17\n" +
	"\x13TASK_STATE_ENQUEUED\x10\x01\x12\x1a\n" +
	"\x16TASK_STATE_IN_PROGRESS\x10\x02\x12\x13\n" +
	"\x0fTASK_STATE_DEAD\x10\x03B#Z!github.com/evrblk/moab/pkg/corepbb\x06proto3"

var (
	file_pkg_corepb_tasks_proto_rawDescOnce sync.Once
	file_pkg_corepb_tasks_proto_rawDescData []byte
)

func file_pkg_corepb_tasks_proto_rawDescGZIP() []byte {
	file_pkg_corepb_tasks_proto_rawDescOnce.Do(func() {
		file_pkg_corepb_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_corepb_tasks_proto_rawDesc), len(file_pkg_corepb_tasks_proto_rawDesc)))
	})
	return file_pkg_corepb_tasks_proto_rawDescData
}

var file_pkg_corepb_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_corepb_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_pkg_corepb_tasks_proto_goTypes = []any{
	(TaskState)(0), // 0: com.evrblk.moab.corepb.TaskState
	(EnqueueRequestEntry_OverwriteOnDuplicate)(0), // 1: com.evrblk.moab.corepb.EnqueueRequestEntry.OverwriteOnDuplicate
	(ReportStatusRequestEntry_Status)(0),          // 2: com.evrblk.moab.corepb.ReportStatusRequestEntry.Status
	(RestartTasksResponseEntry_Result)(0),         // 3: com.evrblk.moab.corepb.RestartTasksResponseEntry.Result
	(*Task)(nil),                                  // 4: com.evrblk.moab.corepb.Task
	(*TaskId)(nil),                                // 5: com.evrblk.moab.corepb.TaskId
	(*ExpirationIndexRecord)(nil),                 // 6: com.evrblk.moab.corepb.ExpirationIndexRecord
	(*Thread)(nil),                                // 7: com.evrblk.moab.corepb.Thread
	(*EnqueueRequest)(nil),                        // 8: com.evrblk.moab.corepb.EnqueueRequest
	(*EnqueueRequestEntry)(nil),                   // 9: com.evrblk.moab.corepb.EnqueueRequestEntry
	(*EnqueueResponse)(nil),                       // 10: com.evrblk.moab.corepb.EnqueueResponse
	(*DequeueRequest)(nil),                        // 11: com.evrblk.moab.corepb.DequeueRequest
	(*DequeueResponse)(nil),                       // 12: com.evrblk.moab.corepb.DequeueResponse
	(*ReportStatusRequest)(nil),                   // 13: com.evrblk.moab.corepb.ReportStatusRequest
	(*ReportStatusRequestEntry)(nil),              // 14: com.evrblk.moab.corepb.ReportStatusRequestEntry
	(*ReportStatusResponse)(nil),                  // 15: com.evrblk.moab.corepb.ReportStatusResponse
	(*DeleteTasksRequest)(nil),                    // 16: com.evrblk.moab.corepb.DeleteTasksRequest
	(*DeleteTasksResponse)(nil),                   // 17: com.evrblk.moab.corepb.DeleteTasksResponse
	(*RestartTasksRequest)(nil),                   // 18: com.evrblk.moab.corepb.RestartTasksRequest
	(*RestartTasksRequestEntry)(nil),              // 19: com.evrblk.moab.corepb.RestartTasksRequestEntry
	(*RestartTasksResponse)(nil),                  // 20: com.evrblk.moab.corepb.RestartTasksResponse
	(*RestartTasksResponseEntry)(nil),             // 21: com.evrblk.moab.corepb.RestartTasksResponseEntry
	(*GetStatisticsRequest)(nil),                  // 22: com.evrblk.moab.corepb.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),                 // 23: com.evrblk.moab.corepb.GetStatisticsResponse
	(*GetTaskRequest)(nil),                        // 24: com.evrblk.moab.corepb.GetTaskRequest
	(*GetTaskResponse)(nil),                       // 25: com.evrblk.moab.corepb.GetTaskResponse
	(*PurgeQueueRequest)(nil),                     // 26: com.evrblk.moab.corepb.PurgeQueueRequest
	(*PurgeQueueResponse)(nil),                    // 27: com.evrblk.moab.corepb.PurgeQueueResponse
	(*ListTasksRequest)(nil),                      // 28: com.evrblk.moab.corepb.ListTasksRequest
	(*ListTasksResponse)(nil),                     // 29: com.evrblk.moab.corepb.ListTasksResponse
	(*RunTasksGarbageCollectionRequest)(nil),      // 30: com.evrblk.moab.corepb.RunTasksGarbageCollectionRequest
	(*RunTasksGarbageCollectionResponse)(nil),     // 31: com.evrblk.moab.corepb.RunTasksGarbageCollectionResponse
	(*TasksCounter)(nil),                          // 32: com.evrblk.moab.corepb.TasksCounter
	(*QueueState)(nil),                            // 33: com.evrblk.moab.corepb.QueueState
	(*RateLimiterState)(nil),                      // 34: com.evrblk.moab.corepb.RateLimiterState
	(*RetryStrategy)(nil),                         // 35: com.evrblk.moab.corepb.RetryStrategy
	(*QueueId)(nil),                               // 36: com.evrblk.moab.corepb.QueueId
	(*DequeuingSettings)(nil),                     // 37: com.evrblk.moab.corepb.DequeuingSettings
	(*DeadLetterQueueConfig)(nil),                 // 38: com.evrblk.moab.corepb.DeadLetterQueueConfig
	(*PaginationToken)(nil),                       // 39: com.evrblk.moab.corepb.PaginationToken
}
var file_pkg_corepb_tasks_proto_depIdxs = []int32{
	5,  // 0: com.evrblk.moab.corepb.Task.id:type_name -> com.evrblk.moab.corepb.TaskId
	0,  // 1: com.evrblk.moab.corepb.Task.state:type_name -> com.evrblk.moab.corepb.TaskState
	35, // 2: com.evrblk.moab.corepb.Task.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	5,  // 3: com.evrblk.moab.corepb.ExpirationIndexRecord.task_id:type_name -> com.evrblk.moab.corepb.TaskId
	5,  // 4: com.evrblk.moab.corepb.Thread.head_task_id:type_name -> com.evrblk.moab.corepb.TaskId
	36, // 5: com.evrblk.moab.corepb.EnqueueRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	9,  // 6: com.evrblk.moab.corepb.EnqueueRequest.entries:type_name -> com.evrblk.moab.corepb.EnqueueRequestEntry
	35, // 7: com.evrblk.moab.corepb.EnqueueRequestEntry.retry_strategy:type_name -> com.evrblk.moab.corepb.RetryStrategy
	1,  // 8: com.evrblk.moab.corepb.EnqueueRequestEntry.overwrite_on_duplicate:type_name -> com.evrblk.moab.corepb.EnqueueRequestEntry.OverwriteOnDuplicate
	4,  // 9: com.evrblk.moab.corepb.EnqueueResponse.tasks:type_name -> com.evrblk.moab.corepb.Task
	36, // 10: com.evrblk.moab.corepb.DequeueRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	37, // 11: com.evrblk.moab.corepb.DequeueRequest.dequeuing_settings:type_name -> com.evrblk.moab.corepb.DequeuingSettings
	38, // 12: com.evrblk.moab.corepb.DequeueRequest.dead_letter_queue_config:type_name -> com.evrblk.moab.corepb.DeadLetterQueueConfig
	4,  // 13: com.evrblk.moab.corepb.DequeueResponse.tasks:type_name -> com.evrblk.moab.corepb.Task
	36, // 14: com.evrblk.moab.corepb.ReportStatusRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	14, // 15: com.evrblk.moab.corepb.ReportStatusRequest.entries:type_name -> com.evrblk.moab.corepb.ReportStatusRequestEntry
	38, // 16: com.evrblk.moab.corepb.ReportStatusRequest.dead_letter_queue_config:type_name -> com.evrblk.moab.corepb.DeadLetterQueueConfig
	5,  // 17: com.evrblk.moab.corepb.ReportStatusRequestEntry.task_id:type_name -> com.evrblk.moab.corepb.TaskId
	2,  // 18: com.evrblk.moab.corepb.ReportStatusRequestEntry.status:type_name -> com.evrblk.moab.corepb.ReportStatusRequestEntry.Status
	36, // 19: com.evrblk.moab.corepb.DeleteTasksRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	36, // 20: com.evrblk.moab.corepb.RestartTasksRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	19, // 21: com.evrblk.moab.corepb.RestartTasksRequest.entries:type_name -> com.evrblk.moab.corepb.RestartTasksRequestEntry
	21, // 22: com.evrblk.moab.corepb.RestartTasksResponse.entries:type_name -> com.evrblk.moab.corepb.RestartTasksResponseEntry
	3,  // 23: com.evrblk.moab.corepb.RestartTasksResponseEntry.result:type_name -> com.evrblk.moab.corepb.RestartTasksResponseEntry.Result
	4,  // 24: com.evrblk.moab.corepb.RestartTasksResponseEntry.task:type_name -> com.evrblk.moab.corepb.Task
	36, // 25: com.evrblk.moab.corepb.GetStatisticsRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	5,  // 26: com.evrblk.moab.corepb.GetTaskRequest.task_id:type_name -> com.evrblk.moab.corepb.TaskId
	4,  // 27: com.evrblk.moab.corepb.GetTaskResponse.task:type_name -> com.evrblk.moab.corepb.Task
	36, // 28: com.evrblk.moab.corepb.PurgeQueueRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	36, // 29: com.evrblk.moab.corepb.ListTasksRequest.queue_id:type_name -> com.evrblk.moab.corepb.QueueId
	39, // 30: com.evrblk.moab.corepb.ListTasksRequest.pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	4,  // 31: com.evrblk.moab.corepb.ListTasksResponse.tasks:type_name -> com.evrblk.moab.corepb.Task
	39, // 32: com.evrblk.moab.corepb.ListTasksResponse.next_pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	39, // 33: com.evrblk.moab.corepb.ListTasksResponse.previous_pagination_token:type_name -> com.evrblk.moab.corepb.PaginationToken
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_pkg_corepb_tasks_proto_init() }
func file_pkg_corepb_tasks_proto_init() {
	if File_pkg_corepb_tasks_proto != nil {
		return
	}
	file_pkg_corepb_common_proto_init()
	file_pkg_corepb_queues_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_corepb_tasks_proto_rawDesc), len(file_pkg_corepb_tasks_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_corepb_tasks_proto_goTypes,
		DependencyIndexes: file_pkg_corepb_tasks_proto_depIdxs,
		EnumInfos:         file_pkg_corepb_tasks_proto_enumTypes,
		MessageInfos:      file_pkg_corepb_tasks_proto_msgTypes,
	}.Build()
	File_pkg_corepb_tasks_proto = out.File
	file_pkg_corepb_tasks_proto_goTypes = nil
	file_pkg_corepb_tasks_proto_depIdxs = nil
}
