// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	"fmt"
	corepb "github.com/evrblk/moab/pkg/corepb"
	monstera "github.com/evrblk/monstera"
	cluster "github.com/evrblk/monstera/cluster"
	mrpc "github.com/evrblk/monstera/rpc"
	prometheus "github.com/prometheus/client_golang/prometheus"
	"io"
	"time"
)

var (
	rpcMethodDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Help:                            "Monstera RPC method duration",
		Name:                            "monstera_rpc_method_duration_seconds",
		NativeHistogramBucketFactor:     1.1,
		NativeHistogramMaxBucketNumber:  100,
		NativeHistogramMinResetDuration: time.Hour,
	}, []string{"node", "core", "method", "shard", "replica"})
	rpcMethodsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Help: "Number of Monstera RPC method calls",
		Name: "monstera_rpc_methods_total",
	}, []string{"node", "core", "method", "shard", "replica"})
)

// RegisterMetrics registers the RPC metrics emitted by the generated core
// adapters with the given registerer. Call once at startup, e.g.
// RegisterMetrics(prometheus.DefaultRegisterer). It panics if a metric is
// already registered.
func RegisterMetrics(registerer prometheus.Registerer) {
	registerer.MustRegister(rpcMethodDuration)
	registerer.MustRegister(rpcMethodsTotal)
}

type MoabQueuesCoreAdapter struct {
	nodeId    string
	shardId   string
	replicaId string

	shardLowerBound cluster.ShardKey
	shardUpperBound cluster.ShardKey

	moabQueuesCore MoabQueuesCoreApi
}

var _ monstera.ApplicationCore = &MoabQueuesCoreAdapter{}

func NewMoabQueuesCoreAdapter(nodeId string, shardId string, replicaId string, shardLowerBound cluster.ShardKey, shardUpperBound cluster.ShardKey, moabQueuesCore MoabQueuesCoreApi) *MoabQueuesCoreAdapter {
	return &MoabQueuesCoreAdapter{
		moabQueuesCore:  moabQueuesCore,
		nodeId:          nodeId,
		replicaId:       replicaId,
		shardId:         shardId,
		shardLowerBound: shardLowerBound,
		shardUpperBound: shardUpperBound,
	}
}

func (a *MoabQueuesCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	return a.moabQueuesCore.Snapshot()
}

func (a *MoabQueuesCoreAdapter) Restore(readers ...io.ReadCloser) error {
	return a.moabQueuesCore.Restore(readers...)
}

func (a *MoabQueuesCoreAdapter) Close() {
	a.moabQueuesCore.Close()
}

func (a *MoabQueuesCoreAdapter) Update(rpcReqBytes []byte) (*monstera.UpdateResponse, error) {
	t1 := time.Now()

	resp := &monstera.UpdateResponse{}
	rpcResp := &mrpc.Response{}
	rpcReq := &mrpc.Request{}

	err := rpcReq.UnmarshalVT(rpcReqBytes)
	if err != nil {
		return nil, err
	}

	switch rpcReq.MethodNumber {
	case 1:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "CreateQueue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "CreateQueue", a.shardId, a.replicaId), t1)

		methodReq := corepb.CreateQueueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.CreateQueue(&CreateQueueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 2:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "UpdateQueue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "UpdateQueue", a.shardId, a.replicaId), t1)

		methodReq := corepb.UpdateQueueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.UpdateQueue(&UpdateQueueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 3:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "DeleteQueue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "DeleteQueue", a.shardId, a.replicaId), t1)

		methodReq := corepb.DeleteQueueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.DeleteQueue(&DeleteQueueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 4:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "CreateSchedule", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "CreateSchedule", a.shardId, a.replicaId), t1)

		methodReq := corepb.CreateScheduleRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.CreateSchedule(&CreateScheduleRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 5:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "UpdateSchedule", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "UpdateSchedule", a.shardId, a.replicaId), t1)

		methodReq := corepb.UpdateScheduleRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.UpdateSchedule(&UpdateScheduleRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 6:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "DeleteSchedule", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "DeleteSchedule", a.shardId, a.replicaId), t1)

		methodReq := corepb.DeleteScheduleRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.DeleteSchedule(&DeleteScheduleRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 7:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "ReportSchedulesStatus", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "ReportSchedulesStatus", a.shardId, a.replicaId), t1)

		methodReq := corepb.ReportSchedulesStatusRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.ReportSchedulesStatus(&ReportSchedulesStatusRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 8:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "RunQueuesGarbageCollection", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "RunQueuesGarbageCollection", a.shardId, a.replicaId), t1)

		methodReq := corepb.RunQueuesGarbageCollectionRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.RunQueuesGarbageCollection(&RunQueuesGarbageCollectionRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	default:
		return nil, fmt.Errorf("no matching handlers")
	}

	rpcRespBytes, err := rpcResp.MarshalVT()
	if err != nil {
		return nil, err
	}
	resp.Data = rpcRespBytes

	return resp, nil
}

func (a *MoabQueuesCoreAdapter) Read(rpcReqBytes []byte) (*monstera.ReadResponse, error) {
	t1 := time.Now()

	resp := &monstera.ReadResponse{}
	rpcResp := &mrpc.Response{}
	rpcReq := &mrpc.Request{}

	err := rpcReq.UnmarshalVT(rpcReqBytes)
	if err != nil {
		return nil, err
	}

	switch rpcReq.MethodNumber {
	case 1:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "GetQueue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "GetQueue", a.shardId, a.replicaId), t1)

		methodReq := corepb.GetQueueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.GetQueue(&GetQueueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 2:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "GetQueueByName", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "GetQueueByName", a.shardId, a.replicaId), t1)

		methodReq := corepb.GetQueueByNameRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.GetQueueByName(&GetQueueByNameRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 3:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "ListQueues", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "ListQueues", a.shardId, a.replicaId), t1)

		methodReq := corepb.ListQueuesRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.ListQueues(&ListQueuesRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 4:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "GetSchedule", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "GetSchedule", a.shardId, a.replicaId), t1)

		methodReq := corepb.GetScheduleRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.GetSchedule(&GetScheduleRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 5:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "DequeSchedules", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "DequeSchedules", a.shardId, a.replicaId), t1)

		methodReq := corepb.DequeSchedulesRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.DequeSchedules(&DequeSchedulesRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 6:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabQueues", "ListSchedules", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabQueues", "ListSchedules", a.shardId, a.replicaId), t1)

		methodReq := corepb.ListSchedulesRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabQueuesCore.ListSchedules(&ListSchedulesRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	default:
		return nil, fmt.Errorf("no matching handlers")
	}

	rpcRespBytes, err := rpcResp.MarshalVT()
	if err != nil {
		return nil, err
	}
	resp.Data = rpcRespBytes

	return resp, nil
}

type MoabTasksCoreAdapter struct {
	nodeId    string
	shardId   string
	replicaId string

	shardLowerBound cluster.ShardKey
	shardUpperBound cluster.ShardKey

	moabTasksCore MoabTasksCoreApi
}

var _ monstera.ApplicationCore = &MoabTasksCoreAdapter{}

func NewMoabTasksCoreAdapter(nodeId string, shardId string, replicaId string, shardLowerBound cluster.ShardKey, shardUpperBound cluster.ShardKey, moabTasksCore MoabTasksCoreApi) *MoabTasksCoreAdapter {
	return &MoabTasksCoreAdapter{
		moabTasksCore:   moabTasksCore,
		nodeId:          nodeId,
		replicaId:       replicaId,
		shardId:         shardId,
		shardLowerBound: shardLowerBound,
		shardUpperBound: shardUpperBound,
	}
}

func (a *MoabTasksCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	return a.moabTasksCore.Snapshot()
}

func (a *MoabTasksCoreAdapter) Restore(readers ...io.ReadCloser) error {
	return a.moabTasksCore.Restore(readers...)
}

func (a *MoabTasksCoreAdapter) Close() {
	a.moabTasksCore.Close()
}

func (a *MoabTasksCoreAdapter) Update(rpcReqBytes []byte) (*monstera.UpdateResponse, error) {
	t1 := time.Now()

	resp := &monstera.UpdateResponse{}
	rpcResp := &mrpc.Response{}
	rpcReq := &mrpc.Request{}

	err := rpcReq.UnmarshalVT(rpcReqBytes)
	if err != nil {
		return nil, err
	}

	switch rpcReq.MethodNumber {
	case 1:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "Enqueue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "Enqueue", a.shardId, a.replicaId), t1)

		methodReq := corepb.EnqueueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.Enqueue(&EnqueueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 2:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "Dequeue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "Dequeue", a.shardId, a.replicaId), t1)

		methodReq := corepb.DequeueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.Dequeue(&DequeueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 3:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "ReportStatus", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "ReportStatus", a.shardId, a.replicaId), t1)

		methodReq := corepb.ReportStatusRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.ReportStatus(&ReportStatusRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 4:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "DeleteTasks", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "DeleteTasks", a.shardId, a.replicaId), t1)

		methodReq := corepb.DeleteTasksRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.DeleteTasks(&DeleteTasksRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 5:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "RestartTasks", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "RestartTasks", a.shardId, a.replicaId), t1)

		methodReq := corepb.RestartTasksRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.RestartTasks(&RestartTasksRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 6:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "PurgeQueue", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "PurgeQueue", a.shardId, a.replicaId), t1)

		methodReq := corepb.PurgeQueueRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.PurgeQueue(&PurgeQueueRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 7:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "RunTasksGarbageCollection", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "RunTasksGarbageCollection", a.shardId, a.replicaId), t1)

		methodReq := corepb.RunTasksGarbageCollectionRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.RunTasksGarbageCollection(&RunTasksGarbageCollectionRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	default:
		return nil, fmt.Errorf("no matching handlers")
	}

	rpcRespBytes, err := rpcResp.MarshalVT()
	if err != nil {
		return nil, err
	}
	resp.Data = rpcRespBytes

	return resp, nil
}

func (a *MoabTasksCoreAdapter) Read(rpcReqBytes []byte) (*monstera.ReadResponse, error) {
	t1 := time.Now()

	resp := &monstera.ReadResponse{}
	rpcResp := &mrpc.Response{}
	rpcReq := &mrpc.Request{}

	err := rpcReq.UnmarshalVT(rpcReqBytes)
	if err != nil {
		return nil, err
	}

	switch rpcReq.MethodNumber {
	case 1:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "GetTask", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "GetTask", a.shardId, a.replicaId), t1)

		methodReq := corepb.GetTaskRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.GetTask(&GetTaskRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	case 2:
		rpcMethodsTotal.WithLabelValues(a.nodeId, "MoabTasks", "GetStatistics", a.shardId, a.replicaId).Inc()
		defer measureSince(rpcMethodDuration.WithLabelValues(a.nodeId, "MoabTasks", "GetStatistics", a.shardId, a.replicaId), t1)

		methodReq := corepb.GetStatisticsRequest{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		if err := checkShardBounds(methodReq.ShardKey(), a.shardLowerBound, a.shardUpperBound); err != nil {
			return nil, err
		}
		methodResp, err := a.moabTasksCore.GetStatistics(&GetStatisticsRequest{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		rpcResp.Error = methodResp.ApplicationError
		if methodResp.Payload != nil {
			methodRespBytes, err := methodResp.Payload.MarshalBinary()
			if err != nil {
				return nil, err
			}
			rpcResp.Data = methodRespBytes
		}
	default:
		return nil, fmt.Errorf("no matching handlers")
	}

	rpcRespBytes, err := rpcResp.MarshalVT()
	if err != nil {
		return nil, err
	}
	resp.Data = rpcRespBytes

	return resp, nil
}

func measureSince(o prometheus.Observer, t1 time.Time) {
	o.Observe(time.Since(t1).Seconds())
}

func checkShardBounds(shardKey, lowerBound, upperBound cluster.ShardKey) error {
	if shardKey < lowerBound || shardKey > upperBound {
		return fmt.Errorf("routing violation: shard key %s is outside shard bounds [%s, %s]", shardKey, lowerBound, upperBound)
	}
	return nil
}
