// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	"context"
	corepb "github.com/evrblk/moab/pkg/corepb"
	monstera "github.com/evrblk/monstera"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
)

type GetQueueRequest = mrpc.ReadRequest[*corepb.GetQueueRequest]
type GetQueueResponse = mrpc.ReadResponse[*corepb.GetQueueResponse]
type GetQueueByNameRequest = mrpc.ReadRequest[*corepb.GetQueueByNameRequest]
type GetQueueByNameResponse = mrpc.ReadResponse[*corepb.GetQueueByNameResponse]
type ListQueuesRequest = mrpc.ReadRequest[*corepb.ListQueuesRequest]
type ListQueuesResponse = mrpc.ReadResponse[*corepb.ListQueuesResponse]
type GetScheduleRequest = mrpc.ReadRequest[*corepb.GetScheduleRequest]
type GetScheduleResponse = mrpc.ReadResponse[*corepb.GetScheduleResponse]
type DequeSchedulesRequest = mrpc.ReadUnshardedRequest[*corepb.DequeSchedulesRequest]
type DequeSchedulesResponse = mrpc.ReadResponse[*corepb.DequeSchedulesResponse]
type ListSchedulesRequest = mrpc.ReadRequest[*corepb.ListSchedulesRequest]
type ListSchedulesResponse = mrpc.ReadResponse[*corepb.ListSchedulesResponse]
type CreateQueueRequest = mrpc.UpdateRequest[*corepb.CreateQueueRequest]
type CreateQueueResponse = mrpc.UpdateResponse[*corepb.CreateQueueResponse]
type UpdateQueueRequest = mrpc.UpdateRequest[*corepb.UpdateQueueRequest]
type UpdateQueueResponse = mrpc.UpdateResponse[*corepb.UpdateQueueResponse]
type DeleteQueueRequest = mrpc.UpdateRequest[*corepb.DeleteQueueRequest]
type DeleteQueueResponse = mrpc.UpdateResponse[*corepb.DeleteQueueResponse]
type CreateScheduleRequest = mrpc.UpdateRequest[*corepb.CreateScheduleRequest]
type CreateScheduleResponse = mrpc.UpdateResponse[*corepb.CreateScheduleResponse]
type UpdateScheduleRequest = mrpc.UpdateRequest[*corepb.UpdateScheduleRequest]
type UpdateScheduleResponse = mrpc.UpdateResponse[*corepb.UpdateScheduleResponse]
type DeleteScheduleRequest = mrpc.UpdateRequest[*corepb.DeleteScheduleRequest]
type DeleteScheduleResponse = mrpc.UpdateResponse[*corepb.DeleteScheduleResponse]
type ReportSchedulesStatusRequest = mrpc.UpdateUnshardedRequest[*corepb.ReportSchedulesStatusRequest]
type ReportSchedulesStatusResponse = mrpc.UpdateResponse[*corepb.ReportSchedulesStatusResponse]
type RunQueuesGarbageCollectionRequest = mrpc.UpdateUnshardedRequest[*corepb.RunQueuesGarbageCollectionRequest]
type RunQueuesGarbageCollectionResponse = mrpc.UpdateResponse[*corepb.RunQueuesGarbageCollectionResponse]
type GetTaskRequest = mrpc.ReadRequest[*corepb.GetTaskRequest]
type GetTaskResponse = mrpc.ReadResponse[*corepb.GetTaskResponse]
type GetStatisticsRequest = mrpc.ReadRequest[*corepb.GetStatisticsRequest]
type GetStatisticsResponse = mrpc.ReadResponse[*corepb.GetStatisticsResponse]
type EnqueueRequest = mrpc.UpdateRequest[*corepb.EnqueueRequest]
type EnqueueResponse = mrpc.UpdateResponse[*corepb.EnqueueResponse]
type DequeueRequest = mrpc.UpdateRequest[*corepb.DequeueRequest]
type DequeueResponse = mrpc.UpdateResponse[*corepb.DequeueResponse]
type ReportStatusRequest = mrpc.UpdateRequest[*corepb.ReportStatusRequest]
type ReportStatusResponse = mrpc.UpdateResponse[*corepb.ReportStatusResponse]
type DeleteTasksRequest = mrpc.UpdateRequest[*corepb.DeleteTasksRequest]
type DeleteTasksResponse = mrpc.UpdateResponse[*corepb.DeleteTasksResponse]
type RestartTasksRequest = mrpc.UpdateRequest[*corepb.RestartTasksRequest]
type RestartTasksResponse = mrpc.UpdateResponse[*corepb.RestartTasksResponse]
type PurgeQueueRequest = mrpc.UpdateRequest[*corepb.PurgeQueueRequest]
type PurgeQueueResponse = mrpc.UpdateResponse[*corepb.PurgeQueueResponse]
type RunTasksGarbageCollectionRequest = mrpc.UpdateUnshardedRequest[*corepb.RunTasksGarbageCollectionRequest]
type RunTasksGarbageCollectionResponse = mrpc.UpdateResponse[*corepb.RunTasksGarbageCollectionResponse]

type MoabClientApi interface {
	GetQueue(ctx context.Context, req *corepb.GetQueueRequest) (*corepb.GetQueueResponse, error)
	GetQueueByName(ctx context.Context, req *corepb.GetQueueByNameRequest) (*corepb.GetQueueByNameResponse, error)
	ListQueues(ctx context.Context, req *corepb.ListQueuesRequest) (*corepb.ListQueuesResponse, error)
	GetSchedule(ctx context.Context, req *corepb.GetScheduleRequest) (*corepb.GetScheduleResponse, error)
	DequeSchedules(ctx context.Context, req *corepb.DequeSchedulesRequest, shardId string) (*corepb.DequeSchedulesResponse, error)
	ListSchedules(ctx context.Context, req *corepb.ListSchedulesRequest) (*corepb.ListSchedulesResponse, error)
	CreateQueue(ctx context.Context, req *corepb.CreateQueueRequest) (*corepb.CreateQueueResponse, error)
	UpdateQueue(ctx context.Context, req *corepb.UpdateQueueRequest) (*corepb.UpdateQueueResponse, error)
	DeleteQueue(ctx context.Context, req *corepb.DeleteQueueRequest) (*corepb.DeleteQueueResponse, error)
	CreateSchedule(ctx context.Context, req *corepb.CreateScheduleRequest) (*corepb.CreateScheduleResponse, error)
	UpdateSchedule(ctx context.Context, req *corepb.UpdateScheduleRequest) (*corepb.UpdateScheduleResponse, error)
	DeleteSchedule(ctx context.Context, req *corepb.DeleteScheduleRequest) (*corepb.DeleteScheduleResponse, error)
	ReportSchedulesStatus(ctx context.Context, req *corepb.ReportSchedulesStatusRequest, shardId string) (*corepb.ReportSchedulesStatusResponse, error)
	RunQueuesGarbageCollection(ctx context.Context, req *corepb.RunQueuesGarbageCollectionRequest, shardId string) (*corepb.RunQueuesGarbageCollectionResponse, error)

	GetTask(ctx context.Context, req *corepb.GetTaskRequest) (*corepb.GetTaskResponse, error)
	GetStatistics(ctx context.Context, req *corepb.GetStatisticsRequest) (*corepb.GetStatisticsResponse, error)
	Enqueue(ctx context.Context, req *corepb.EnqueueRequest) (*corepb.EnqueueResponse, error)
	Dequeue(ctx context.Context, req *corepb.DequeueRequest) (*corepb.DequeueResponse, error)
	ReportStatus(ctx context.Context, req *corepb.ReportStatusRequest) (*corepb.ReportStatusResponse, error)
	DeleteTasks(ctx context.Context, req *corepb.DeleteTasksRequest) (*corepb.DeleteTasksResponse, error)
	RestartTasks(ctx context.Context, req *corepb.RestartTasksRequest) (*corepb.RestartTasksResponse, error)
	PurgeQueue(ctx context.Context, req *corepb.PurgeQueueRequest) (*corepb.PurgeQueueResponse, error)
	RunTasksGarbageCollection(ctx context.Context, req *corepb.RunTasksGarbageCollectionRequest, shardId string) (*corepb.RunTasksGarbageCollectionResponse, error)

	ListShards(applicationName string) ([]string, error)
}
type MoabQueuesCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetQueue(req *GetQueueRequest) (*GetQueueResponse, error)
	GetQueueByName(req *GetQueueByNameRequest) (*GetQueueByNameResponse, error)
	ListQueues(req *ListQueuesRequest) (*ListQueuesResponse, error)
	GetSchedule(req *GetScheduleRequest) (*GetScheduleResponse, error)
	DequeSchedules(req *DequeSchedulesRequest) (*DequeSchedulesResponse, error)
	ListSchedules(req *ListSchedulesRequest) (*ListSchedulesResponse, error)
	CreateQueue(req *CreateQueueRequest) (*CreateQueueResponse, error)
	UpdateQueue(req *UpdateQueueRequest) (*UpdateQueueResponse, error)
	DeleteQueue(req *DeleteQueueRequest) (*DeleteQueueResponse, error)
	CreateSchedule(req *CreateScheduleRequest) (*CreateScheduleResponse, error)
	UpdateSchedule(req *UpdateScheduleRequest) (*UpdateScheduleResponse, error)
	DeleteSchedule(req *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	ReportSchedulesStatus(req *ReportSchedulesStatusRequest) (*ReportSchedulesStatusResponse, error)
	RunQueuesGarbageCollection(req *RunQueuesGarbageCollectionRequest) (*RunQueuesGarbageCollectionResponse, error)
}

type MoabTasksCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(readers ...io.ReadCloser) error
	Close()
	GetTask(req *GetTaskRequest) (*GetTaskResponse, error)
	GetStatistics(req *GetStatisticsRequest) (*GetStatisticsResponse, error)
	Enqueue(req *EnqueueRequest) (*EnqueueResponse, error)
	Dequeue(req *DequeueRequest) (*DequeueResponse, error)
	ReportStatus(req *ReportStatusRequest) (*ReportStatusResponse, error)
	DeleteTasks(req *DeleteTasksRequest) (*DeleteTasksResponse, error)
	RestartTasks(req *RestartTasksRequest) (*RestartTasksResponse, error)
	PurgeQueue(req *PurgeQueueRequest) (*PurgeQueueResponse, error)
	RunTasksGarbageCollection(req *RunTasksGarbageCollectionRequest) (*RunTasksGarbageCollectionResponse, error)
}
