// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	"context"
	"fmt"
	corepb "github.com/evrblk/moab/pkg/corepb"
	monstera "github.com/evrblk/monstera"
	cluster "github.com/evrblk/monstera/cluster"
	mrpc "github.com/evrblk/monstera/rpc"
	"log/slog"
	"sort"
	"sync"
	"time"
)

func nilifyIfEmpty(err *mrpc.Error) error {
	if err == nil || err.Code == mrpc.ErrorCode_INVALID || err.Code == mrpc.ErrorCode_OK {
		return nil
	} else {
		return err
	}
}

type MoabMonsteraStub struct {
	monsteraClient *monstera.Client
}

var _ MoabClientApi = &MoabMonsteraStub{}

func (s *MoabMonsteraStub) GetQueue(ctx context.Context, methodReq *corepb.GetQueueRequest, opts ...mrpc.CallOption) (*corepb.GetQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     1,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetQueueByName(ctx context.Context, methodReq *corepb.GetQueueByNameRequest, opts ...mrpc.CallOption) (*corepb.GetQueueByNameResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     2,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetQueueByNameResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListQueues(ctx context.Context, methodReq *corepb.ListQueuesRequest, opts ...mrpc.CallOption) (*corepb.ListQueuesResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     3,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ListQueuesResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetSchedule(ctx context.Context, methodReq *corepb.GetScheduleRequest, opts ...mrpc.CallOption) (*corepb.GetScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     4,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DequeSchedules(ctx context.Context, methodReq *corepb.DequeSchedulesRequest, shardId string, opts ...mrpc.CallOption) (*corepb.DequeSchedulesResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     5,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.ReadShard(ctx, "MoabQueues", shardId, false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DequeSchedulesResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListSchedules(ctx context.Context, methodReq *corepb.ListSchedulesRequest, opts ...mrpc.CallOption) (*corepb.ListSchedulesResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     6,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ListSchedulesResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) CreateQueue(ctx context.Context, methodReq *corepb.CreateQueueRequest, opts ...mrpc.CallOption) (*corepb.CreateQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     1,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.CreateQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) UpdateQueue(ctx context.Context, methodReq *corepb.UpdateQueueRequest, opts ...mrpc.CallOption) (*corepb.UpdateQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     2,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.UpdateQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DeleteQueue(ctx context.Context, methodReq *corepb.DeleteQueueRequest, opts ...mrpc.CallOption) (*corepb.DeleteQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     3,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DeleteQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) CreateSchedule(ctx context.Context, methodReq *corepb.CreateScheduleRequest, opts ...mrpc.CallOption) (*corepb.CreateScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     4,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.CreateScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) UpdateSchedule(ctx context.Context, methodReq *corepb.UpdateScheduleRequest, opts ...mrpc.CallOption) (*corepb.UpdateScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     5,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.UpdateScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DeleteSchedule(ctx context.Context, methodReq *corepb.DeleteScheduleRequest, opts ...mrpc.CallOption) (*corepb.DeleteScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     6,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DeleteScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ReportSchedulesStatus(ctx context.Context, methodReq *corepb.ReportSchedulesStatusRequest, shardId string, opts ...mrpc.CallOption) (*corepb.ReportSchedulesStatusResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     7,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.UpdateShard(ctx, "MoabQueues", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ReportSchedulesStatusResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RunQueuesGarbageCollection(ctx context.Context, methodReq *corepb.RunQueuesGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunQueuesGarbageCollectionResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     8,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.UpdateShard(ctx, "MoabQueues", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RunQueuesGarbageCollectionResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) SwapQueueId(ctx context.Context, methodReq *corepb.SwapQueueIdRequest, opts ...mrpc.CallOption) (*corepb.SwapQueueIdResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     9,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.SwapQueueIdResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetTask(ctx context.Context, methodReq *corepb.GetTaskRequest, opts ...mrpc.CallOption) (*corepb.GetTaskResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     1,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabTasks", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetTaskResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetStatistics(ctx context.Context, methodReq *corepb.GetStatisticsRequest, opts ...mrpc.CallOption) (*corepb.GetStatisticsResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     2,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabTasks", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetStatisticsResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListTasks(ctx context.Context, methodReq *corepb.ListTasksRequest, opts ...mrpc.CallOption) (*corepb.ListTasksResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     3,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MoabTasks", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ListTasksResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) Enqueue(ctx context.Context, methodReq *corepb.EnqueueRequest, opts ...mrpc.CallOption) (*corepb.EnqueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     1,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.EnqueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) Dequeue(ctx context.Context, methodReq *corepb.DequeueRequest, opts ...mrpc.CallOption) (*corepb.DequeueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     2,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DequeueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ReportStatus(ctx context.Context, methodReq *corepb.ReportStatusRequest, opts ...mrpc.CallOption) (*corepb.ReportStatusResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     3,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ReportStatusResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DeleteTasks(ctx context.Context, methodReq *corepb.DeleteTasksRequest, opts ...mrpc.CallOption) (*corepb.DeleteTasksResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     4,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DeleteTasksResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RestartTasks(ctx context.Context, methodReq *corepb.RestartTasksRequest, opts ...mrpc.CallOption) (*corepb.RestartTasksResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     5,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RestartTasksResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) PurgeQueue(ctx context.Context, methodReq *corepb.PurgeQueueRequest, opts ...mrpc.CallOption) (*corepb.PurgeQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     6,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.PurgeQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RunTasksGarbageCollection(ctx context.Context, methodReq *corepb.RunTasksGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunTasksGarbageCollectionResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     7,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.UpdateShard(ctx, "MoabTasks", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RunTasksGarbageCollectionResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RunPurgeQueueGarbageCollection(ctx context.Context, methodReq *corepb.RunPurgeQueueGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunPurgeQueueGarbageCollectionResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     8,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.UpdateShard(ctx, "MoabTasks", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RunPurgeQueueGarbageCollectionResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListShards(applicationName string) ([]string, error) {
	shards, err := s.monsteraClient.ListShards(applicationName)
	if err != nil {
		return nil, err
	}
	shardIds := make([]string, len(shards))
	for i := range shards {
		shardIds[i] = shards[i].Id
	}
	return shardIds, nil
}

func NewMoabMonsteraStub(monsteraClient *monstera.Client) *MoabMonsteraStub {
	return &MoabMonsteraStub{monsteraClient: monsteraClient}
}

type moabQueuesCoreNonclusteredAdapter struct {
	core       MoabQueuesCoreApi
	mu         sync.RWMutex
	id         string
	lowerBound cluster.ShardKey
	upperBound cluster.ShardKey
}

type moabTasksCoreNonclusteredAdapter struct {
	core       MoabTasksCoreApi
	mu         sync.RWMutex
	id         string
	lowerBound cluster.ShardKey
	upperBound cluster.ShardKey
}

type MoabNonclusteredApplicationCoresFactory struct {
	MoabQueuesCoreFactoryFunc func(shardId string, lowerBound cluster.ShardKey, upperBound cluster.ShardKey) MoabQueuesCoreApi
	MoabTasksCoreFactoryFunc  func(shardId string, lowerBound cluster.ShardKey, upperBound cluster.ShardKey) MoabTasksCoreApi
}
type MoabNonclusteredStub struct {
	moabQueuesCores []*moabQueuesCoreNonclusteredAdapter
	moabTasksCores  []*moabTasksCoreNonclusteredAdapter
	logger          *slog.Logger
}

var _ MoabClientApi = &MoabNonclusteredStub{}

func (s *MoabNonclusteredStub) findMoabQueuesAdapter(shardKey cluster.ShardKey) (*moabQueuesCoreNonclusteredAdapter, error) {
	adapters := s.moabQueuesCores
	i := sort.Search(len(adapters), func(i int) bool {
		return adapters[i].lowerBound > shardKey
	})
	if i > 0 {
		candidate := adapters[i-1]
		if shardKey <= candidate.upperBound {
			return candidate, nil
		}
	}
	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) findMoabTasksAdapter(shardKey cluster.ShardKey) (*moabTasksCoreNonclusteredAdapter, error) {
	adapters := s.moabTasksCores
	i := sort.Search(len(adapters), func(i int) bool {
		return adapters[i].lowerBound > shardKey
	})
	if i > 0 {
		candidate := adapters[i-1]
		if shardKey <= candidate.upperBound {
			return candidate, nil
		}
	}
	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) GetQueue(ctx context.Context, req *corepb.GetQueueRequest, opts ...mrpc.CallOption) (*corepb.GetQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.GetQueue(&mrpc.ReadRequest[*corepb.GetQueueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) GetQueueByName(ctx context.Context, req *corepb.GetQueueByNameRequest, opts ...mrpc.CallOption) (*corepb.GetQueueByNameResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.GetQueueByName(&mrpc.ReadRequest[*corepb.GetQueueByNameRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) ListQueues(ctx context.Context, req *corepb.ListQueuesRequest, opts ...mrpc.CallOption) (*corepb.ListQueuesResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.ListQueues(&mrpc.ReadRequest[*corepb.ListQueuesRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) GetSchedule(ctx context.Context, req *corepb.GetScheduleRequest, opts ...mrpc.CallOption) (*corepb.GetScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.GetSchedule(&mrpc.ReadRequest[*corepb.GetScheduleRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) DequeSchedules(ctx context.Context, req *corepb.DequeSchedulesRequest, shardId string, opts ...mrpc.CallOption) (*corepb.DequeSchedulesResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.moabQueuesCores {
		if adapter.id == shardId {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.DequeSchedules(&mrpc.ReadUnshardedRequest[*corepb.DequeSchedulesRequest]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) ListSchedules(ctx context.Context, req *corepb.ListSchedulesRequest, opts ...mrpc.CallOption) (*corepb.ListSchedulesResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.ListSchedules(&mrpc.ReadRequest[*corepb.ListSchedulesRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) CreateQueue(ctx context.Context, req *corepb.CreateQueueRequest, opts ...mrpc.CallOption) (*corepb.CreateQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.CreateQueue(&mrpc.UpdateRequest[*corepb.CreateQueueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) UpdateQueue(ctx context.Context, req *corepb.UpdateQueueRequest, opts ...mrpc.CallOption) (*corepb.UpdateQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.UpdateQueue(&mrpc.UpdateRequest[*corepb.UpdateQueueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) DeleteQueue(ctx context.Context, req *corepb.DeleteQueueRequest, opts ...mrpc.CallOption) (*corepb.DeleteQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.DeleteQueue(&mrpc.UpdateRequest[*corepb.DeleteQueueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) CreateSchedule(ctx context.Context, req *corepb.CreateScheduleRequest, opts ...mrpc.CallOption) (*corepb.CreateScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.CreateSchedule(&mrpc.UpdateRequest[*corepb.CreateScheduleRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) UpdateSchedule(ctx context.Context, req *corepb.UpdateScheduleRequest, opts ...mrpc.CallOption) (*corepb.UpdateScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.UpdateSchedule(&mrpc.UpdateRequest[*corepb.UpdateScheduleRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) DeleteSchedule(ctx context.Context, req *corepb.DeleteScheduleRequest, opts ...mrpc.CallOption) (*corepb.DeleteScheduleResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.DeleteSchedule(&mrpc.UpdateRequest[*corepb.DeleteScheduleRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) ReportSchedulesStatus(ctx context.Context, req *corepb.ReportSchedulesStatusRequest, shardId string, opts ...mrpc.CallOption) (*corepb.ReportSchedulesStatusResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.moabQueuesCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.ReportSchedulesStatus(&mrpc.UpdateUnshardedRequest[*corepb.ReportSchedulesStatusRequest]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) RunQueuesGarbageCollection(ctx context.Context, req *corepb.RunQueuesGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunQueuesGarbageCollectionResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.moabQueuesCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.RunQueuesGarbageCollection(&mrpc.UpdateUnshardedRequest[*corepb.RunQueuesGarbageCollectionRequest]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) SwapQueueId(ctx context.Context, req *corepb.SwapQueueIdRequest, opts ...mrpc.CallOption) (*corepb.SwapQueueIdResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabQueuesAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.SwapQueueId(&mrpc.UpdateRequest[*corepb.SwapQueueIdRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) GetTask(ctx context.Context, req *corepb.GetTaskRequest, opts ...mrpc.CallOption) (*corepb.GetTaskResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.GetTask(&mrpc.ReadRequest[*corepb.GetTaskRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) GetStatistics(ctx context.Context, req *corepb.GetStatisticsRequest, opts ...mrpc.CallOption) (*corepb.GetStatisticsResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.GetStatistics(&mrpc.ReadRequest[*corepb.GetStatisticsRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) ListTasks(ctx context.Context, req *corepb.ListTasksRequest, opts ...mrpc.CallOption) (*corepb.ListTasksResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.RLock()
	defer adapter.mu.RUnlock()

	resp, err := adapter.core.ListTasks(&mrpc.ReadRequest[*corepb.ListTasksRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) Enqueue(ctx context.Context, req *corepb.EnqueueRequest, opts ...mrpc.CallOption) (*corepb.EnqueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.Enqueue(&mrpc.UpdateRequest[*corepb.EnqueueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) Dequeue(ctx context.Context, req *corepb.DequeueRequest, opts ...mrpc.CallOption) (*corepb.DequeueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.Dequeue(&mrpc.UpdateRequest[*corepb.DequeueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) ReportStatus(ctx context.Context, req *corepb.ReportStatusRequest, opts ...mrpc.CallOption) (*corepb.ReportStatusResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.ReportStatus(&mrpc.UpdateRequest[*corepb.ReportStatusRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) DeleteTasks(ctx context.Context, req *corepb.DeleteTasksRequest, opts ...mrpc.CallOption) (*corepb.DeleteTasksResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.DeleteTasks(&mrpc.UpdateRequest[*corepb.DeleteTasksRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) RestartTasks(ctx context.Context, req *corepb.RestartTasksRequest, opts ...mrpc.CallOption) (*corepb.RestartTasksResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.RestartTasks(&mrpc.UpdateRequest[*corepb.RestartTasksRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) PurgeQueue(ctx context.Context, req *corepb.PurgeQueueRequest, opts ...mrpc.CallOption) (*corepb.PurgeQueueResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	adapter, err := s.findMoabTasksAdapter(shardKey)
	if err != nil {
		return nil, err
	}

	adapter.mu.Lock()
	defer adapter.mu.Unlock()

	resp, err := adapter.core.PurgeQueue(&mrpc.UpdateRequest[*corepb.PurgeQueueRequest]{
		Now:     now,
		Payload: req,
	}, s.logger)
	if err != nil {
		return nil, err
	}
	err = nilifyIfEmpty(resp.ApplicationError)
	if err != nil {
		return nil, err
	}
	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}
	return resp.Payload, nil
}

func (s *MoabNonclusteredStub) RunTasksGarbageCollection(ctx context.Context, req *corepb.RunTasksGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunTasksGarbageCollectionResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.moabTasksCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.RunTasksGarbageCollection(&mrpc.UpdateUnshardedRequest[*corepb.RunTasksGarbageCollectionRequest]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) RunPurgeQueueGarbageCollection(ctx context.Context, req *corepb.RunPurgeQueueGarbageCollectionRequest, shardId string, opts ...mrpc.CallOption) (*corepb.RunPurgeQueueGarbageCollectionResponse, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.moabTasksCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.RunPurgeQueueGarbageCollection(&mrpc.UpdateUnshardedRequest[*corepb.RunPurgeQueueGarbageCollectionRequest]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) ListShards(applicationName string) ([]string, error) {
	switch applicationName {
	case "MoabQueues":
		shardIds := make([]string, len(s.moabQueuesCores))
		for i := range s.moabQueuesCores {
			shardIds[i] = s.moabQueuesCores[i].id
		}
		return shardIds, nil
	case "MoabTasks":
		shardIds := make([]string, len(s.moabTasksCores))
		for i := range s.moabTasksCores {
			shardIds[i] = s.moabTasksCores[i].id
		}
		return shardIds, nil
	default:
		return nil, fmt.Errorf("application not found: %s", applicationName)
	}
}

func NewMoabNonclusteredStub(shardsPerApp int, coresFactory *MoabNonclusteredApplicationCoresFactory, logger *slog.Logger) *MoabNonclusteredStub {
	if shardsPerApp < 1 || int64(shardsPerApp) > int64(cluster.KeyspacePerApplication) || shardsPerApp&(shardsPerApp-1) != 0 {
		panic(fmt.Sprintf("shardsPerApp must be a power of 2 between 1 and 2^32, got %d", shardsPerApp))
	}

	if logger == nil {
		logger = slog.Default()
	}

	moabQueuesCores := make([]*moabQueuesCoreNonclusteredAdapter, shardsPerApp)
	moabTasksCores := make([]*moabTasksCoreNonclusteredAdapter, shardsPerApp)

	shardSize := int64(cluster.KeyspacePerApplication) / int64(shardsPerApp)
	for i := 0; i < shardsPerApp; i++ {
		lowerBound := cluster.ShardKey(int64(i) * shardSize)
		upperBound := cluster.ShardKey(int64(i+1)*shardSize - 1)

		sl, su := cluster.ShortenBounds(lowerBound.Bytes(), upperBound.Bytes())

		moabQueuesShardId := fmt.Sprintf("%s_%x_%x", "MoabQueues", sl, su)
		moabQueuesCores[i] = &moabQueuesCoreNonclusteredAdapter{core: coresFactory.MoabQueuesCoreFactoryFunc(moabQueuesShardId, lowerBound, upperBound), id: moabQueuesShardId, lowerBound: lowerBound, upperBound: upperBound}

		moabTasksShardId := fmt.Sprintf("%s_%x_%x", "MoabTasks", sl, su)
		moabTasksCores[i] = &moabTasksCoreNonclusteredAdapter{core: coresFactory.MoabTasksCoreFactoryFunc(moabTasksShardId, lowerBound, upperBound), id: moabTasksShardId, lowerBound: lowerBound, upperBound: upperBound}

	}
	return &MoabNonclusteredStub{moabQueuesCores: moabQueuesCores, moabTasksCores: moabTasksCores, logger: logger}
}
