// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	"context"
	"fmt"
	corepb "github.com/evrblk/moab/pkg/corepb"
	monstera "github.com/evrblk/monstera"
	cluster "github.com/evrblk/monstera/cluster"
	mrpc "github.com/evrblk/monstera/rpc"
	"sync"
	"time"
)

func nilifyIfEmpty(err *mrpc.Error) error {
	if err == nil || err.Code == mrpc.ErrorCode_INVALID || err.Code == mrpc.ErrorCode_OK {
		return nil
	} else {
		return err
	}
}

type MoabMonsteraStub struct {
	monsteraClient *monstera.Client
}

var _ MoabClientApi = &MoabMonsteraStub{}

func (s *MoabMonsteraStub) GetQueue(ctx context.Context, methodReq *corepb.GetQueueRequest) (*corepb.GetQueueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 1,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetQueueByName(ctx context.Context, methodReq *corepb.GetQueueByNameRequest) (*corepb.GetQueueByNameResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 2,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetQueueByNameResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListQueues(ctx context.Context, methodReq *corepb.ListQueuesRequest) (*corepb.ListQueuesResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 3,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ListQueuesResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetSchedule(ctx context.Context, methodReq *corepb.GetScheduleRequest) (*corepb.GetScheduleResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 4,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DequeSchedules(ctx context.Context, methodReq *corepb.DequeSchedulesRequest, shardId string) (*corepb.DequeSchedulesResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 5,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.ReadShard(ctx, "MoabQueues", shardId, false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DequeSchedulesResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListSchedules(ctx context.Context, methodReq *corepb.ListSchedulesRequest) (*corepb.ListSchedulesResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 6,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabQueues", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ListSchedulesResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) CreateQueue(ctx context.Context, methodReq *corepb.CreateQueueRequest) (*corepb.CreateQueueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 1,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.CreateQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) UpdateQueue(ctx context.Context, methodReq *corepb.UpdateQueueRequest) (*corepb.UpdateQueueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 2,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.UpdateQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DeleteQueue(ctx context.Context, methodReq *corepb.DeleteQueueRequest) (*corepb.DeleteQueueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 3,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DeleteQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) CreateSchedule(ctx context.Context, methodReq *corepb.CreateScheduleRequest) (*corepb.CreateScheduleResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 4,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.CreateScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) UpdateSchedule(ctx context.Context, methodReq *corepb.UpdateScheduleRequest) (*corepb.UpdateScheduleResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 5,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.UpdateScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DeleteSchedule(ctx context.Context, methodReq *corepb.DeleteScheduleRequest) (*corepb.DeleteScheduleResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 6,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabQueues", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DeleteScheduleResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ReportSchedulesStatus(ctx context.Context, methodReq *corepb.ReportSchedulesStatusRequest, shardId string) (*corepb.ReportSchedulesStatusResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 7,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.UpdateShard(ctx, "MoabQueues", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ReportSchedulesStatusResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RunQueuesGarbageCollection(ctx context.Context, methodReq *corepb.RunQueuesGarbageCollectionRequest, shardId string) (*corepb.RunQueuesGarbageCollectionResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 8,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.UpdateShard(ctx, "MoabQueues", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RunQueuesGarbageCollectionResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetTask(ctx context.Context, methodReq *corepb.GetTaskRequest) (*corepb.GetTaskResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 1,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabTasks", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetTaskResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) GetStatistics(ctx context.Context, methodReq *corepb.GetStatisticsRequest) (*corepb.GetStatisticsResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 2,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MoabTasks", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.GetStatisticsResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) Enqueue(ctx context.Context, methodReq *corepb.EnqueueRequest) (*corepb.EnqueueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 1,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.EnqueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) Dequeue(ctx context.Context, methodReq *corepb.DequeueRequest) (*corepb.DequeueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 2,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DequeueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ReportStatus(ctx context.Context, methodReq *corepb.ReportStatusRequest) (*corepb.ReportStatusResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 3,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.ReportStatusResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) DeleteTasks(ctx context.Context, methodReq *corepb.DeleteTasksRequest) (*corepb.DeleteTasksResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 4,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.DeleteTasksResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RestartTasks(ctx context.Context, methodReq *corepb.RestartTasksRequest) (*corepb.RestartTasksResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 5,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RestartTasksResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) PurgeQueue(ctx context.Context, methodReq *corepb.PurgeQueueRequest) (*corepb.PurgeQueueResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 6,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MoabTasks", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.PurgeQueueResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) RunTasksGarbageCollection(ctx context.Context, methodReq *corepb.RunTasksGarbageCollectionRequest, shardId string) (*corepb.RunTasksGarbageCollectionResponse, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 7,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.UpdateShard(ctx, "MoabTasks", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &corepb.RunTasksGarbageCollectionResponse{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MoabMonsteraStub) ListShards(applicationName string) ([]string, error) {
	shards, err := s.monsteraClient.ListShards(applicationName)
	if err != nil {
		return nil, err
	}
	shardIds := make([]string, len(shards))
	for i := range shards {
		shardIds[i] = shards[i].Id
	}
	return shardIds, nil
}

func NewMoabMonsteraStub(monsteraClient *monstera.Client) *MoabMonsteraStub {
	return &MoabMonsteraStub{monsteraClient: monsteraClient}
}

type moabQueuesCoreNonclusteredAdapter struct {
	core       MoabQueuesCoreApi
	mu         sync.RWMutex
	id         string
	lowerBound cluster.ShardKey
	upperBound cluster.ShardKey
}

type moabTasksCoreNonclusteredAdapter struct {
	core       MoabTasksCoreApi
	mu         sync.RWMutex
	id         string
	lowerBound cluster.ShardKey
	upperBound cluster.ShardKey
}

type MoabNonclusteredApplicationCoresFactory struct {
	MoabQueuesCoreFactoryFunc func(shardId string, lowerBound cluster.ShardKey, upperBound cluster.ShardKey) MoabQueuesCoreApi
	MoabTasksCoreFactoryFunc  func(shardId string, lowerBound cluster.ShardKey, upperBound cluster.ShardKey) MoabTasksCoreApi
}
type MoabNonclusteredStub struct {
	moabQueuesCores []*moabQueuesCoreNonclusteredAdapter
	moabTasksCores  []*moabTasksCoreNonclusteredAdapter
}

var _ MoabClientApi = &MoabNonclusteredStub{}

func (s *MoabNonclusteredStub) GetQueue(ctx context.Context, req *corepb.GetQueueRequest) (*corepb.GetQueueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.GetQueue(&mrpc.ReadRequest[*corepb.GetQueueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) GetQueueByName(ctx context.Context, req *corepb.GetQueueByNameRequest) (*corepb.GetQueueByNameResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.GetQueueByName(&mrpc.ReadRequest[*corepb.GetQueueByNameRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) ListQueues(ctx context.Context, req *corepb.ListQueuesRequest) (*corepb.ListQueuesResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.ListQueues(&mrpc.ReadRequest[*corepb.ListQueuesRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) GetSchedule(ctx context.Context, req *corepb.GetScheduleRequest) (*corepb.GetScheduleResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.GetSchedule(&mrpc.ReadRequest[*corepb.GetScheduleRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) DequeSchedules(ctx context.Context, req *corepb.DequeSchedulesRequest, shardId string) (*corepb.DequeSchedulesResponse, error) {
	for _, adapter := range s.moabQueuesCores {
		if adapter.id == shardId {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.DequeSchedules(&mrpc.ReadUnshardedRequest[*corepb.DequeSchedulesRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) ListSchedules(ctx context.Context, req *corepb.ListSchedulesRequest) (*corepb.ListSchedulesResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.ListSchedules(&mrpc.ReadRequest[*corepb.ListSchedulesRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) CreateQueue(ctx context.Context, req *corepb.CreateQueueRequest) (*corepb.CreateQueueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.CreateQueue(&mrpc.UpdateRequest[*corepb.CreateQueueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) UpdateQueue(ctx context.Context, req *corepb.UpdateQueueRequest) (*corepb.UpdateQueueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.UpdateQueue(&mrpc.UpdateRequest[*corepb.UpdateQueueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) DeleteQueue(ctx context.Context, req *corepb.DeleteQueueRequest) (*corepb.DeleteQueueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.DeleteQueue(&mrpc.UpdateRequest[*corepb.DeleteQueueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) CreateSchedule(ctx context.Context, req *corepb.CreateScheduleRequest) (*corepb.CreateScheduleResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.CreateSchedule(&mrpc.UpdateRequest[*corepb.CreateScheduleRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) UpdateSchedule(ctx context.Context, req *corepb.UpdateScheduleRequest) (*corepb.UpdateScheduleResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.UpdateSchedule(&mrpc.UpdateRequest[*corepb.UpdateScheduleRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) DeleteSchedule(ctx context.Context, req *corepb.DeleteScheduleRequest) (*corepb.DeleteScheduleResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabQueuesCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.DeleteSchedule(&mrpc.UpdateRequest[*corepb.DeleteScheduleRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) ReportSchedulesStatus(ctx context.Context, req *corepb.ReportSchedulesStatusRequest, shardId string) (*corepb.ReportSchedulesStatusResponse, error) {
	for _, adapter := range s.moabQueuesCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.ReportSchedulesStatus(&mrpc.UpdateUnshardedRequest[*corepb.ReportSchedulesStatusRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) RunQueuesGarbageCollection(ctx context.Context, req *corepb.RunQueuesGarbageCollectionRequest, shardId string) (*corepb.RunQueuesGarbageCollectionResponse, error) {
	for _, adapter := range s.moabQueuesCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.RunQueuesGarbageCollection(&mrpc.UpdateUnshardedRequest[*corepb.RunQueuesGarbageCollectionRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) GetTask(ctx context.Context, req *corepb.GetTaskRequest) (*corepb.GetTaskResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.GetTask(&mrpc.ReadRequest[*corepb.GetTaskRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) GetStatistics(ctx context.Context, req *corepb.GetStatisticsRequest) (*corepb.GetStatisticsResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.GetStatistics(&mrpc.ReadRequest[*corepb.GetStatisticsRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) Enqueue(ctx context.Context, req *corepb.EnqueueRequest) (*corepb.EnqueueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.Enqueue(&mrpc.UpdateRequest[*corepb.EnqueueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) Dequeue(ctx context.Context, req *corepb.DequeueRequest) (*corepb.DequeueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.Dequeue(&mrpc.UpdateRequest[*corepb.DequeueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) ReportStatus(ctx context.Context, req *corepb.ReportStatusRequest) (*corepb.ReportStatusResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.ReportStatus(&mrpc.UpdateRequest[*corepb.ReportStatusRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) DeleteTasks(ctx context.Context, req *corepb.DeleteTasksRequest) (*corepb.DeleteTasksResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.DeleteTasks(&mrpc.UpdateRequest[*corepb.DeleteTasksRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) RestartTasks(ctx context.Context, req *corepb.RestartTasksRequest) (*corepb.RestartTasksResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.RestartTasks(&mrpc.UpdateRequest[*corepb.RestartTasksRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) PurgeQueue(ctx context.Context, req *corepb.PurgeQueueRequest) (*corepb.PurgeQueueResponse, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.moabTasksCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.PurgeQueue(&mrpc.UpdateRequest[*corepb.PurgeQueueRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MoabNonclusteredStub) RunTasksGarbageCollection(ctx context.Context, req *corepb.RunTasksGarbageCollectionRequest, shardId string) (*corepb.RunTasksGarbageCollectionResponse, error) {
	for _, adapter := range s.moabTasksCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.RunTasksGarbageCollection(&mrpc.UpdateUnshardedRequest[*corepb.RunTasksGarbageCollectionRequest]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MoabNonclusteredStub) ListShards(applicationName string) ([]string, error) {
	switch applicationName {
	case "MoabQueues":
		shardIds := make([]string, len(s.moabQueuesCores))
		for i := range s.moabQueuesCores {
			shardIds[i] = s.moabQueuesCores[i].id
		}
		return shardIds, nil
	case "MoabTasks":
		shardIds := make([]string, len(s.moabTasksCores))
		for i := range s.moabTasksCores {
			shardIds[i] = s.moabTasksCores[i].id
		}
		return shardIds, nil
	default:
		return nil, fmt.Errorf("application not found: %s", applicationName)
	}
}

func NewMoabNonclusteredStub(shardsPerApp int, coresFactory *MoabNonclusteredApplicationCoresFactory) *MoabNonclusteredStub {
	if shardsPerApp < 1 || int64(shardsPerApp) > int64(cluster.KeyspacePerApplication) || shardsPerApp&(shardsPerApp-1) != 0 {
		panic(fmt.Sprintf("shardsPerApp must be a power of 2 between 1 and 2^32, got %d", shardsPerApp))
	}

	moabQueuesCores := make([]*moabQueuesCoreNonclusteredAdapter, shardsPerApp)
	moabTasksCores := make([]*moabTasksCoreNonclusteredAdapter, shardsPerApp)

	shardSize := int64(cluster.KeyspacePerApplication) / int64(shardsPerApp)
	for i := 0; i < shardsPerApp; i++ {
		lowerBound := cluster.ShardKey(int64(i) * shardSize)
		upperBound := cluster.ShardKey(int64(i+1)*shardSize - 1)

		sl, su := cluster.ShortenBounds(lowerBound.Bytes(), upperBound.Bytes())

		moabQueuesShardId := fmt.Sprintf("%s_%x_%x", "MoabQueues", sl, su)
		moabQueuesCores[i] = &moabQueuesCoreNonclusteredAdapter{core: coresFactory.MoabQueuesCoreFactoryFunc(moabQueuesShardId, lowerBound, upperBound), id: moabQueuesShardId, lowerBound: lowerBound, upperBound: upperBound}

		moabTasksShardId := fmt.Sprintf("%s_%x_%x", "MoabTasks", sl, su)
		moabTasksCores[i] = &moabTasksCoreNonclusteredAdapter{core: coresFactory.MoabTasksCoreFactoryFunc(moabTasksShardId, lowerBound, upperBound), id: moabTasksShardId, lowerBound: lowerBound, upperBound: upperBound}

	}
	return &MoabNonclusteredStub{moabQueuesCores: moabQueuesCores, moabTasksCores: moabTasksCores}
}
