// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	monstera "github.com/evrblk/monstera"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
	"log/slog"
)

type MoabQueuesValidatingCore struct {
	core MoabQueuesCoreApi
}

var _ MoabQueuesCoreApi = &MoabQueuesValidatingCore{}

func NewMoabQueuesValidatingCore(core MoabQueuesCoreApi) *MoabQueuesValidatingCore {
	return &MoabQueuesValidatingCore{core: core}
}

func (v *MoabQueuesValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *MoabQueuesValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *MoabQueuesValidatingCore) Close() {
	v.core.Close()
}

func (v *MoabQueuesValidatingCore) GetQueue(req *GetQueueRequest, log *slog.Logger) (*GetQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetQueue(req, log)
}

func (v *MoabQueuesValidatingCore) GetQueueByName(req *GetQueueByNameRequest, log *slog.Logger) (*GetQueueByNameResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetQueueByNameResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetQueueByName(req, log)
}

func (v *MoabQueuesValidatingCore) ListQueues(req *ListQueuesRequest, log *slog.Logger) (*ListQueuesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListQueuesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListQueues(req, log)
}

func (v *MoabQueuesValidatingCore) GetSchedule(req *GetScheduleRequest, log *slog.Logger) (*GetScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetSchedule(req, log)
}

func (v *MoabQueuesValidatingCore) DequeSchedules(req *DequeSchedulesRequest, log *slog.Logger) (*DequeSchedulesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DequeSchedulesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DequeSchedules(req, log)
}

func (v *MoabQueuesValidatingCore) ListSchedules(req *ListSchedulesRequest, log *slog.Logger) (*ListSchedulesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSchedulesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSchedules(req, log)
}

func (v *MoabQueuesValidatingCore) CreateQueue(req *CreateQueueRequest, log *slog.Logger) (*CreateQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateQueue(req, log)
}

func (v *MoabQueuesValidatingCore) UpdateQueue(req *UpdateQueueRequest, log *slog.Logger) (*UpdateQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateQueue(req, log)
}

func (v *MoabQueuesValidatingCore) DeleteQueue(req *DeleteQueueRequest, log *slog.Logger) (*DeleteQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteQueue(req, log)
}

func (v *MoabQueuesValidatingCore) CreateSchedule(req *CreateScheduleRequest, log *slog.Logger) (*CreateScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateSchedule(req, log)
}

func (v *MoabQueuesValidatingCore) UpdateSchedule(req *UpdateScheduleRequest, log *slog.Logger) (*UpdateScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateSchedule(req, log)
}

func (v *MoabQueuesValidatingCore) DeleteSchedule(req *DeleteScheduleRequest, log *slog.Logger) (*DeleteScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteSchedule(req, log)
}

func (v *MoabQueuesValidatingCore) ReportSchedulesStatus(req *ReportSchedulesStatusRequest, log *slog.Logger) (*ReportSchedulesStatusResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ReportSchedulesStatusResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ReportSchedulesStatus(req, log)
}

func (v *MoabQueuesValidatingCore) RunQueuesGarbageCollection(req *RunQueuesGarbageCollectionRequest, log *slog.Logger) (*RunQueuesGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunQueuesGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunQueuesGarbageCollection(req, log)
}

func (v *MoabQueuesValidatingCore) SwapQueueId(req *SwapQueueIdRequest, log *slog.Logger) (*SwapQueueIdResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &SwapQueueIdResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.SwapQueueId(req, log)
}

type MoabTasksValidatingCore struct {
	core MoabTasksCoreApi
}

var _ MoabTasksCoreApi = &MoabTasksValidatingCore{}

func NewMoabTasksValidatingCore(core MoabTasksCoreApi) *MoabTasksValidatingCore {
	return &MoabTasksValidatingCore{core: core}
}

func (v *MoabTasksValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *MoabTasksValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *MoabTasksValidatingCore) Close() {
	v.core.Close()
}

func (v *MoabTasksValidatingCore) GetTask(req *GetTaskRequest, log *slog.Logger) (*GetTaskResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetTaskResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetTask(req, log)
}

func (v *MoabTasksValidatingCore) GetStatistics(req *GetStatisticsRequest, log *slog.Logger) (*GetStatisticsResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetStatisticsResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetStatistics(req, log)
}

func (v *MoabTasksValidatingCore) ListTasks(req *ListTasksRequest, log *slog.Logger) (*ListTasksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListTasksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListTasks(req, log)
}

func (v *MoabTasksValidatingCore) Enqueue(req *EnqueueRequest, log *slog.Logger) (*EnqueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &EnqueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Enqueue(req, log)
}

func (v *MoabTasksValidatingCore) Dequeue(req *DequeueRequest, log *slog.Logger) (*DequeueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DequeueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Dequeue(req, log)
}

func (v *MoabTasksValidatingCore) ReportStatus(req *ReportStatusRequest, log *slog.Logger) (*ReportStatusResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ReportStatusResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ReportStatus(req, log)
}

func (v *MoabTasksValidatingCore) DeleteTasks(req *DeleteTasksRequest, log *slog.Logger) (*DeleteTasksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteTasksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteTasks(req, log)
}

func (v *MoabTasksValidatingCore) RestartTasks(req *RestartTasksRequest, log *slog.Logger) (*RestartTasksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RestartTasksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RestartTasks(req, log)
}

func (v *MoabTasksValidatingCore) PurgeQueue(req *PurgeQueueRequest, log *slog.Logger) (*PurgeQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &PurgeQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.PurgeQueue(req, log)
}

func (v *MoabTasksValidatingCore) RunTasksGarbageCollection(req *RunTasksGarbageCollectionRequest, log *slog.Logger) (*RunTasksGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunTasksGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunTasksGarbageCollection(req, log)
}

func (v *MoabTasksValidatingCore) RunPurgeQueueGarbageCollection(req *RunPurgeQueueGarbageCollectionRequest, log *slog.Logger) (*RunPurgeQueueGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunPurgeQueueGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunPurgeQueueGarbageCollection(req, log)
}
