// Code generated by `monstera code generate`. DO NOT EDIT.

package coreapis

import (
	monstera "github.com/evrblk/monstera"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
)

type MoabQueuesValidatingCore struct {
	core MoabQueuesCoreApi
}

var _ MoabQueuesCoreApi = &MoabQueuesValidatingCore{}

func NewMoabQueuesValidatingCore(core MoabQueuesCoreApi) *MoabQueuesValidatingCore {
	return &MoabQueuesValidatingCore{core: core}
}

func (v *MoabQueuesValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *MoabQueuesValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *MoabQueuesValidatingCore) Close() {
	v.core.Close()
}

func (v *MoabQueuesValidatingCore) GetQueue(req *GetQueueRequest) (*GetQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetQueue(req)
}

func (v *MoabQueuesValidatingCore) GetQueueByName(req *GetQueueByNameRequest) (*GetQueueByNameResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetQueueByNameResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetQueueByName(req)
}

func (v *MoabQueuesValidatingCore) ListQueues(req *ListQueuesRequest) (*ListQueuesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListQueuesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListQueues(req)
}

func (v *MoabQueuesValidatingCore) GetSchedule(req *GetScheduleRequest) (*GetScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetSchedule(req)
}

func (v *MoabQueuesValidatingCore) DequeSchedules(req *DequeSchedulesRequest) (*DequeSchedulesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DequeSchedulesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DequeSchedules(req)
}

func (v *MoabQueuesValidatingCore) ListSchedules(req *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListSchedulesResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListSchedules(req)
}

func (v *MoabQueuesValidatingCore) CreateQueue(req *CreateQueueRequest) (*CreateQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateQueue(req)
}

func (v *MoabQueuesValidatingCore) UpdateQueue(req *UpdateQueueRequest) (*UpdateQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateQueue(req)
}

func (v *MoabQueuesValidatingCore) DeleteQueue(req *DeleteQueueRequest) (*DeleteQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteQueue(req)
}

func (v *MoabQueuesValidatingCore) CreateSchedule(req *CreateScheduleRequest) (*CreateScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &CreateScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.CreateSchedule(req)
}

func (v *MoabQueuesValidatingCore) UpdateSchedule(req *UpdateScheduleRequest) (*UpdateScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &UpdateScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.UpdateSchedule(req)
}

func (v *MoabQueuesValidatingCore) DeleteSchedule(req *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteScheduleResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteSchedule(req)
}

func (v *MoabQueuesValidatingCore) ReportSchedulesStatus(req *ReportSchedulesStatusRequest) (*ReportSchedulesStatusResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ReportSchedulesStatusResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ReportSchedulesStatus(req)
}

func (v *MoabQueuesValidatingCore) RunQueuesGarbageCollection(req *RunQueuesGarbageCollectionRequest) (*RunQueuesGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunQueuesGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunQueuesGarbageCollection(req)
}

func (v *MoabQueuesValidatingCore) SwapQueueId(req *SwapQueueIdRequest) (*SwapQueueIdResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &SwapQueueIdResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.SwapQueueId(req)
}

type MoabTasksValidatingCore struct {
	core MoabTasksCoreApi
}

var _ MoabTasksCoreApi = &MoabTasksValidatingCore{}

func NewMoabTasksValidatingCore(core MoabTasksCoreApi) *MoabTasksValidatingCore {
	return &MoabTasksValidatingCore{core: core}
}

func (v *MoabTasksValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *MoabTasksValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *MoabTasksValidatingCore) Close() {
	v.core.Close()
}

func (v *MoabTasksValidatingCore) GetTask(req *GetTaskRequest) (*GetTaskResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetTaskResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetTask(req)
}

func (v *MoabTasksValidatingCore) GetStatistics(req *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &GetStatisticsResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.GetStatistics(req)
}

func (v *MoabTasksValidatingCore) ListTasks(req *ListTasksRequest) (*ListTasksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ListTasksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ListTasks(req)
}

func (v *MoabTasksValidatingCore) Enqueue(req *EnqueueRequest) (*EnqueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &EnqueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Enqueue(req)
}

func (v *MoabTasksValidatingCore) Dequeue(req *DequeueRequest) (*DequeueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DequeueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Dequeue(req)
}

func (v *MoabTasksValidatingCore) ReportStatus(req *ReportStatusRequest) (*ReportStatusResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &ReportStatusResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.ReportStatus(req)
}

func (v *MoabTasksValidatingCore) DeleteTasks(req *DeleteTasksRequest) (*DeleteTasksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &DeleteTasksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.DeleteTasks(req)
}

func (v *MoabTasksValidatingCore) RestartTasks(req *RestartTasksRequest) (*RestartTasksResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RestartTasksResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RestartTasks(req)
}

func (v *MoabTasksValidatingCore) PurgeQueue(req *PurgeQueueRequest) (*PurgeQueueResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &PurgeQueueResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.PurgeQueue(req)
}

func (v *MoabTasksValidatingCore) RunTasksGarbageCollection(req *RunTasksGarbageCollectionRequest) (*RunTasksGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunTasksGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunTasksGarbageCollection(req)
}

func (v *MoabTasksValidatingCore) RunPurgeQueueGarbageCollection(req *RunPurgeQueueGarbageCollectionRequest) (*RunPurgeQueueGarbageCollectionResponse, error) {
	if err := req.Payload.Validate(); err != nil {
		return &RunPurgeQueueGarbageCollectionResponse{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.RunPurgeQueueGarbageCollection(req)
}
